In [129]:
! pip install requests

Requirement already satisfied: requests in /Users/rahulshrivastav/Desktop/NHL Analytics Hub/venv/lib/python3.14/site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/rahulshrivastav/Desktop/NHL Analytics Hub/venv/lib/python3.14/site-packages (from requests) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/rahulshrivastav/Desktop/NHL Analytics Hub/venv/lib/python3.14/site-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/rahulshrivastav/Desktop/NHL Analytics Hub/venv/lib/python3.14/site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /Users/rahulshrivastav/Desktop/NHL Analytics Hub/venv/lib/python3.14/site-packages (from requests) (2026.7.22)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [130]:
import requests

url = "https://api-web.nhle.com/v1/standings/now"
response = requests.get(url)
data = response.json()
data

{'wildCardIndicator': True,
 'standingsDateTimeUtc': '2026-09-15T10:57:02Z',
 'standings': [{'clinchIndicator': 'p',
   'conferenceAbbrev': 'W',
   'conferenceHomeSequence': 1,
   'conferenceL10Sequence': 2,
   'conferenceName': 'Western',
   'conferenceRoadSequence': 1,
   'conferenceSequence': 1,
   'date': '2026-04-17',
   'divisionAbbrev': 'C',
   'divisionHomeSequence': 1,
   'divisionL10Sequence': 1,
   'divisionName': 'Central',
   'divisionRoadSequence': 1,
   'divisionSequence': 1,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 99,
   'goalDifferentialPctg': 1.207317,
   'goalAgainst': 203,
   'goalFor': 302,
   'goalsForPctg': 3.682927,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 49,
   'homeGoalsAgainst': 108,
   'homeGoalsFor': 157,
   'homeLosses': 9,
   'homeOtLosses': 6,
   'homePoints': 58,
   'homeRegulationPlusOtWins': 25,
   'homeRegulationWins': 25,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 14,
   'l10GoalsAgainst': 20,
   'l10GoalsFor': 34,
   'l10Losses': 2,
   'l10OtLosses': 1,
   'l10Points': 15,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 3,
   'leagueL10Sequence': 4,
   'leagueRoadSequence': 1,
   'leagueSequence': 1,
   'losses': 16,
   'otLosses': 11,
   'placeName': {'default': 'Colorado'},
   'pointPctg': 0.737805,
   'points': 121,
   'regulationPlusOtWinPctg': 0.621951,
   'regulationPlusOtWins': 51,
   'regulationWinPctg': 0.585366,
   'regulationWins': 48,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 50,
   'roadGoalsAgainst': 95,
   'roadGoalsFor': 145,
   'roadLosses': 7,
   'roadOtLosses': 5,
   'roadPoints': 63,
   'roadRegulationPlusOtWins': 26,
   'roadRegulationWins': 23,
   'roadTies': 0,
   'roadWins': 29,
   'seasonId': 20252026,
   'shootoutLosses': 6,
   'shootoutWins': 4,
   'streakCode': 'W',
   'streakCount': 3,
   'teamName': {'default': 'Colorado Avalanche',
    'fr': 'Avalanche du Colorado'},
   'teamCommonName': {'default': 'Avalanche'},
   'teamAbbrev': {'default': 'COL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/COL_dark.svg',
   'ties': 0,
   'waiversSequence': 32,
   'wildcardSequence': 0,
   'winPctg': 0.670732,
   'wins': 55},
  {'clinchIndicator': 'z',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 1,
   'conferenceL10Sequence': 2,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 3,
   'conferenceSequence': 1,
   'date': '2026-04-17',
   'divisionAbbrev': 'M',
   'divisionHomeSequence': 1,
   'divisionL10Sequence': 2,
   'divisionName': 'Metropolitan',
   'divisionRoadSequence': 1,
   'divisionSequence': 1,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 56,
   'goalDifferentialPctg': 0.682927,
   'goalAgainst': 240,
   'goalFor': 296,
   'goalsForPctg': 3.609756,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 35,
   'homeGoalsAgainst': 126,
   'homeGoalsFor': 161,
   'homeLosses': 10,
   'homeOtLosses': 2,
   'homePoints': 60,
   'homeRegulationPlusOtWins': 27,
   'homeRegulationWins': 20,
   'homeTies': 0,
   'homeWins': 29,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 12,
   'l10GoalsAgainst': 27,
   'l10GoalsFor': 39,
   'l10Losses': 2,
   'l10OtLosses': 1,
   'l10Points': 15,
   'l10RegulationPlusOtWins': 7,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 1,
   'leagueL10Sequence': 3,
   'leagueRoadSequence': 5,
   'leagueSequence': 2,
   'losses': 22,
   'otLosses': 7,
   'placeName': {'default': 'Carolina', 'fr': 'Caroline'},
   'pointPctg': 0.689024,
   'points': 113,
   'regulationPlusOtWinPctg': 0.585366,
   'regulationPlusOtWins': 48,
   'regulationWinPctg': 0.47561,
   'regulationWins': 39,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 21,
   'roadGoalsAgainst': 114,
   'roadGoalsFor': 135,
   'roadLosses': 12,
   'roadOtLosses': 5,
   'roadPoints': 53,
   'roadRegulationPlusOtWins': 21,
   'roadRegulationWins': 19,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 4,
   'shootoutWins': 5,
   'streakCode': 'W',
   'streakCount': 1,
   'teamName': {'default': 'Carolina Hurricanes',
    'fr': 'Hurricanes de la Caroline'},
   'teamCommonName': {'default': 'Hurricanes'},
   'teamAbbrev': {'default': 'CAR'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/CAR_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/CAR_dark.svg',
   'ties': 0,
   'waiversSequence': 31,
   'wildcardSequence': 0,
   'winPctg': 0.646341,
   'wins': 53},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'W',
   'conferenceHomeSequence': 2,
   'conferenceL10Sequence': 3,
   'conferenceName': 'Western',
   'conferenceRoadSequence': 2,
   'conferenceSequence': 2,
   'date': '2026-04-17',
   'divisionAbbrev': 'C',
   'divisionHomeSequence': 2,
   'divisionL10Sequence': 2,
   'divisionName': 'Central',
   'divisionRoadSequence': 2,
   'divisionSequence': 2,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 53,
   'goalDifferentialPctg': 0.646341,
   'goalAgainst': 226,
   'goalFor': 279,
   'goalsForPctg': 3.402439,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 23,
   'homeGoalsAgainst': 112,
   'homeGoalsFor': 135,
   'homeLosses': 11,
   'homeOtLosses': 4,
   'homePoints': 56,
   'homeRegulationPlusOtWins': 24,
   'homeRegulationWins': 19,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 6,
   'l10GoalsAgainst': 28,
   'l10GoalsFor': 34,
   'l10Losses': 2,
   'l10OtLosses': 1,
   'l10Points': 15,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 5,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 5,
   'leagueL10Sequence': 5,
   'leagueRoadSequence': 2,
   'leagueSequence': 3,
   'losses': 20,
   'otLosses': 12,
   'placeName': {'default': 'Dallas'},
   'pointPctg': 0.682927,
   'points': 112,
   'regulationPlusOtWinPctg': 0.536585,
   'regulationPlusOtWins': 44,
   'regulationWinPctg': 0.463415,
   'regulationWins': 38,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 30,
   'roadGoalsAgainst': 114,
   'roadGoalsFor': 144,
   'roadLosses': 9,
   'roadOtLosses': 8,
   'roadPoints': 56,
   'roadRegulationPlusOtWins': 20,
   'roadRegulationWins': 19,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 4,
   'shootoutWins': 6,
   'streakCode': 'W',
   'streakCount': 5,
   'teamName': {'default': 'Dallas Stars', 'fr': 'Stars de Dallas'},
   'teamCommonName': {'default': 'Stars'},
   'teamAbbrev': {'default': 'DAL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/DAL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/DAL_dark.svg',
   'ties': 0,
   'waiversSequence': 30,
   'wildcardSequence': 0,
   'winPctg': 0.609756,
   'wins': 50},
  {'clinchIndicator': 'y',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 3,
   'conferenceL10Sequence': 6,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 4,
   'conferenceSequence': 2,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 2,
   'divisionL10Sequence': 3,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 3,
   'divisionSequence': 1,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 47,
   'goalDifferentialPctg': 0.573171,
   'goalAgainst': 241,
   'goalFor': 288,
   'goalsForPctg': 3.512195,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 30,
   'homeGoalsAgainst': 119,
   'homeGoalsFor': 149,
   'homeLosses': 10,
   'homeOtLosses': 5,
   'homePoints': 57,
   'homeRegulationPlusOtWins': 22,
   'homeRegulationWins': 22,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 4,
   'l10GoalsAgainst': 30,
   'l10GoalsFor': 34,
   'l10Losses': 3,
   'l10OtLosses': 1,
   'l10Points': 13,
   'l10RegulationPlusOtWins': 5,
   'l10RegulationWins': 5,
   'l10Ties': 0,
   'l10Wins': 6,
   'leagueHomeSequence': 4,
   'leagueL10Sequence': 12,
   'leagueRoadSequence': 6,
   'leagueSequence': 4,
   'losses': 23,
   'otLosses': 9,
   'placeName': {'default': 'Buffalo'},
   'pointPctg': 0.664634,
   'points': 109,
   'regulationPlusOtWinPctg': 0.54878,
   'regulationPlusOtWins': 45,
   'regulationWinPctg': 0.512195,
   'regulationWins': 42,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 17,
   'roadGoalsAgainst': 122,
   'roadGoalsFor': 139,
   'roadLosses': 13,
   'roadOtLosses': 4,
   'roadPoints': 52,
   'roadRegulationPlusOtWins': 23,
   'roadRegulationWins': 20,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 1,
   'shootoutWins': 5,
   'streakCode': 'OT',
   'streakCount': 1,
   'teamName': {'default': 'Buffalo Sabres', 'fr': 'Sabres de Buffalo'},
   'teamCommonName': {'default': 'Sabres'},
   'teamAbbrev': {'default': 'BUF'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/BUF_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/BUF_dark.svg',
   'ties': 0,
   'waiversSequence': 29,
   'wildcardSequence': 0,
   'winPctg': 0.609756,
   'wins': 50},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 5,
   'conferenceL10Sequence': 12,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 2,
   'conferenceSequence': 3,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 3,
   'divisionL10Sequence': 6,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 2,
   'divisionSequence': 2,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 59,
   'goalDifferentialPctg': 0.719512,
   'goalAgainst': 231,
   'goalFor': 290,
   'goalsForPctg': 3.536585,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 22,
   'homeGoalsAgainst': 115,
   'homeGoalsFor': 137,
   'homeLosses': 14,
   'homeOtLosses': 1,
   'homePoints': 53,
   'homeRegulationPlusOtWins': 24,
   'homeRegulationWins': 19,
   'homeTies': 0,
   'homeWins': 26,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': -4,
   'l10GoalsAgainst': 30,
   'l10GoalsFor': 26,
   'l10Losses': 5,
   'l10OtLosses': 0,
   'l10Points': 10,
   'l10RegulationPlusOtWins': 5,
   'l10RegulationWins': 4,
   'l10Ties': 0,
   'l10Wins': 5,
   'leagueHomeSequence': 8,
   'leagueL10Sequence': 21,
   'leagueRoadSequence': 4,
   'leagueSequence': 5,
   'losses': 26,
   'otLosses': 6,
   'placeName': {'default': 'Tampa Bay'},
   'pointPctg': 0.646341,
   'points': 106,
   'regulationPlusOtWinPctg': 0.560976,
   'regulationPlusOtWins': 46,
   'regulationWinPctg': 0.487805,
   'regulationWins': 40,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 37,
   'roadGoalsAgainst': 116,
   'roadGoalsFor': 153,
   'roadLosses': 12,
   'roadOtLosses': 5,
   'roadPoints': 53,
   'roadRegulationPlusOtWins': 22,
   'roadRegulationWins': 21,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 2,
   'shootoutWins': 4,
   'streakCode': 'L',
   'streakCount': 1,
   'teamName': {'default': 'Tampa Bay Lightning',
    'fr': 'Lightning de Tampa Bay'},
   'teamCommonName': {'default': 'Lightning'},
   'teamAbbrev': {'default': 'TBL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/TBL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/TBL_dark.svg',
   'ties': 0,
   'waiversSequence': 28,
   'wildcardSequence': 0,
   'winPctg': 0.609756,
   'wins': 50},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 7,
   'conferenceL10Sequence': 3,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 1,
   'conferenceSequence': 4,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 5,
   'divisionL10Sequence': 1,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 1,
   'divisionSequence': 3,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 27,
   'goalDifferentialPctg': 0.329268,
   'goalAgainst': 256,
   'goalFor': 283,
   'goalsForPctg': 3.45122,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 10,
   'homeGoalsAgainst': 127,
   'homeGoalsFor': 137,
   'homeLosses': 15,
   'homeOtLosses': 2,
   'homePoints': 50,
   'homeRegulationPlusOtWins': 22,
   'homeRegulationWins': 17,
   'homeTies': 0,
   'homeWins': 24,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 4,
   'l10GoalsAgainst': 24,
   'l10GoalsFor': 28,
   'l10Losses': 3,
   'l10OtLosses': 0,
   'l10Points': 14,
   'l10RegulationPlusOtWins': 5,
   'l10RegulationWins': 5,
   'l10Ties': 0,
   'l10Wins': 7,
   'leagueHomeSequence': 12,
   'leagueL10Sequence': 7,
   'leagueRoadSequence': 3,
   'leagueSequence': 6,
   'losses': 24,
   'otLosses': 10,
   'placeName': {'default': 'Montréal'},
   'pointPctg': 0.646341,
   'points': 106,
   'regulationPlusOtWinPctg': 0.536585,
   'regulationPlusOtWins': 44,
   'regulationWinPctg': 0.414634,
   'regulationWins': 34,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 17,
   'roadGoalsAgainst': 129,
   'roadGoalsFor': 146,
   'roadLosses': 9,
   'roadOtLosses': 8,
   'roadPoints': 56,
   'roadRegulationPlusOtWins': 22,
   'roadRegulationWins': 17,
   'roadTies': 0,
   'roadWins': 24,
   'seasonId': 20252026,
   'shootoutLosses': 5,
   'shootoutWins': 4,
   'streakCode': 'L',
   'streakCount': 1,
   'teamName': {'default': 'Montréal Canadiens',
    'fr': 'Canadiens de Montréal'},
   'teamCommonName': {'default': 'Canadiens'},
   'teamAbbrev': {'default': 'MTL'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MTL_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/MTL_dark.svg',
   'ties': 0,
   'waiversSequence': 27,
   'wildcardSequence': 0,
   'winPctg': 0.585366,
   'wins': 48},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'W',
   'conferenceHomeSequence': 3,
   'conferenceL10Sequence': 7,
   'conferenceName': 'Western',
   'conferenceRoadSequence': 4,
   'conferenceSequence': 3,
   'date': '2026-04-17',
   'divisionAbbrev': 'C',
   'divisionHomeSequence': 3,
   'divisionL10Sequence': 4,
   'divisionName': 'Central',
   'divisionRoadSequence': 3,
   'divisionSequence': 3,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 32,
   'goalDifferentialPctg': 0.390244,
   'goalAgainst': 240,
   'goalFor': 272,
   'goalsForPctg': 3.317073,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 15,
   'homeGoalsAgainst': 115,
   'homeGoalsFor': 130,
   'homeLosses': 10,
   'homeOtLosses': 8,
   'homePoints': 54,
   'homeRegulationPlusOtWins': 19,
   'homeRegulationWins': 14,
   'homeTies': 0,
   'homeWins': 23,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 4,
   'l10GoalsAgainst': 32,
   'l10GoalsFor': 36,
   'l10Losses': 4,
   'l10OtLosses': 0,
   'l10Points': 12,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 6,
   'leagueHomeSequence': 7,
   'leagueL10Sequence': 14,
   'leagueRoadSequence': 9,
   'leagueSequence': 7,
   'losses': 24,
   'otLosses': 12,
   'placeName': {'default': 'Minnesota'},
   'pointPctg': 0.634146,
   'points': 104,
   'regulationPlusOtWinPctg': 0.512195,
   'regulationPlusOtWins': 42,
   'regulationWinPctg': 0.378049,
   'regulationWins': 31,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 17,
   'roadGoalsAgainst': 125,
   'roadGoalsFor': 142,
   'roadLosses': 14,
   'roadOtLosses': 4,
   'roadPoints': 50,
   'roadRegulationPlusOtWins': 23,
   'roadRegulationWins': 17,
   'roadTies': 0,
   'roadWins': 23,
   'seasonId': 20252026,
   'shootoutLosses': 5,
   'shootoutWins': 4,
   'streakCode': 'W',
   'streakCount': 1,
   'teamName': {'default': 'Minnesota Wild', 'fr': 'Wild du Minnesota'},
   'teamCommonName': {'default': 'Wild'},
   'teamAbbrev': {'default': 'MIN'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MIN_light.svg',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/MIN_dark.svg',
   'ties': 0,
   'waiversSequence': 26,
   'wildcardSequence': 0,
   'winPctg': 0.560976,
   'wins': 46},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 2,
   'conferenceL10Sequence': 8,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 13,
   'conferenceSequence': 5,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 1,
   'divisionL10Sequence': 4,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 6,
   'divisionSequence': 4,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 22,
   'goalDifferentialPctg': 0.268293,
   'goalAgainst': 250,
   'goalFor': 272,
   'goalsForPctg': 3.317073,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 40,
   'homeGoalsAgainst': 105,
   'homeGoalsFor': 145,
   'homeLosses': 11,
   'homeOtLosses': 1,
   'homePoints': 59,
   'homeRegulationPlusOtWins': 28,
   'homeRegulationWins': 23,
   'homeTies': 0,
   'homeWins': 29,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 6,
   'l10GoalsAgainst': 26,
   'l10GoalsFor': 32,
   'l10Losses': 3,
   'l10OtLosses': 2,
   'l10Points': 12,
   'l10RegulationPlusOtWins': 4,
   'l10RegulationWins': 4,
   'l10Ties': 0,
   'l10Wins': 5,
   'leagueHomeSequence': 2,
   'leagueL10Sequence': 16,
   'leagueRoadSequence': 21,
   'leagueSequence': 8,
   'losses': 27,
   'otLosses': 10,
   'placeName': {'default': 'Boston'},
   'pointPctg': 0.609756,
   'points': 100,
   'regulationPlusOtWinPctg': 0.5,
   'regulationPlusOtWins': 41,
   'regulationWinPctg': 0.402439,
   'regulationWins': 33,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': -18,
   'roadGoalsAgainst': 145,
   'roadGoalsFor': 127,
   'roadLosses': 16,
   'roadOtLosses': 9,
   'roadPoints': 41,
   'roadRegulationPlusOtWins': 13,
   'roadRegulationWins': 10,
   'roadTies': 0,
   'roadWins': 16,
   'seasonId': 20252026,
   'shootoutLosses': 3,
   'shootoutWins': 4,
   'streakCode': 'W',
   'streakCount': 2,
   'teamName': {'default': 'Boston Bruins', 'fr': 'Bruins de Boston'},
   'teamCommonName': {'default': 'Bruins'},
   'teamAbbrev': {'default': 'BOS'},
   'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/BOS_light.svg?season=20252026',
   'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/BOS_dark.svg?season=20252026',
   'ties': 0,
   'waiversSequence': 25,
   'wildcardSequence': 1,
   'winPctg': 0.54878,
   'wins': 45},
  {'clinchIndicator': 'x',
   'conferenceAbbrev': 'E',
   'conferenceHomeSequence': 6,
   'conferenceL10Sequence': 5,
   'conferenceName': 'Eastern',
   'conferenceRoadSequence': 7,
   'conferenceSequence': 6,
   'date': '2026-04-17',
   'divisionAbbrev': 'A',
   'divisionHomeSequence': 4,
   'divisionL10Sequence': 2,
   'divisionName': 'Atlantic',
   'divisionRoadSequence': 4,
   'divisionSequence': 5,
   'gameTypeId': 2,
   'gamesPlayed': 82,
   'goalDifferential': 32,
   'goalDifferentialPctg': 0.390244,
   'goalAgainst': 246,
   'goalFor': 278,
   'goalsForPctg': 3.390244,
   'homeGamesPlayed': 41,
   'homeGoalDifferential': 31,
   'homeGoalsAgainst': 108,
   'homeGoalsFor': 139,
   'homeLosses': 12,
   'homeOtLosses': 6,
   'homePoints': 52,
   'homeRegulationPlusOtWins': 21,
   'homeRegulationWins': 21,
   'homeTies': 0,
   'homeWins': 23,
   'l10GamesPlayed': 10,
   'l10GoalDifferential': 10,
   'l10GoalsAgainst': 26,
   'l10GoalsFor': 36,
   'l10Losses': 3,
   'l10OtLosses': 1,
   'l10Points': 13,
   'l10RegulationPlusOtWins': 6,
   'l10RegulationWins': 6,
   'l10Ties': 0,
   'l10Wins': 6,
   'leagueHomeSequence': 9,
   'leagueL10Sequence': 10,
   'leagueRoadSequence': 11,
   'leagueSequence': 9,
   'losses': 27,
   'otLosses': 11,
   'placeName': {'default': 'Ottawa'},
   'pointPctg': 0.603659,
   'points': 99,
   'regulationPlusOtWinPctg': 0.5,
   'regulationPlusOtWins': 41,
   'regulationWinPctg': 0.463415,
   'regulationWins': 38,
   'roadGamesPlayed': 41,
   'roadGoalDifferential': 1,
   'roadGoalsAgainst': 138,
   'roadGoalsFor': 139,
   'roadLosses': 15,
   'roadOtLosses': 5,
   'roadPoints': 47,
   'roadRegulationPlusOtWins': 20,
   'roadRegulationWins': 17,

In [131]:
data.keys()

dict_keys(['wildCardIndicator', 'standingsDateTimeUtc', 'standings'])

In [132]:
data['standings']

[{'clinchIndicator': 'p',
  'conferenceAbbrev': 'W',
  'conferenceHomeSequence': 1,
  'conferenceL10Sequence': 2,
  'conferenceName': 'Western',
  'conferenceRoadSequence': 1,
  'conferenceSequence': 1,
  'date': '2026-04-17',
  'divisionAbbrev': 'C',
  'divisionHomeSequence': 1,
  'divisionL10Sequence': 1,
  'divisionName': 'Central',
  'divisionRoadSequence': 1,
  'divisionSequence': 1,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 99,
  'goalDifferentialPctg': 1.207317,
  'goalAgainst': 203,
  'goalFor': 302,
  'goalsForPctg': 3.682927,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 49,
  'homeGoalsAgainst': 108,
  'homeGoalsFor': 157,
  'homeLosses': 9,
  'homeOtLosses': 6,
  'homePoints': 58,
  'homeRegulationPlusOtWins': 25,
  'homeRegulationWins': 25,
  'homeTies': 0,
  'homeWins': 26,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 14,
  'l10GoalsAgainst': 20,
  'l10GoalsFor': 34,
  'l10Losses': 2,
  'l10OtLosses': 1,
  'l10Points': 15,
  'l10RegulationPlusOtWins': 6,
  'l10RegulationWins': 6,
  'l10Ties': 0,
  'l10Wins': 7,
  'leagueHomeSequence': 3,
  'leagueL10Sequence': 4,
  'leagueRoadSequence': 1,
  'leagueSequence': 1,
  'losses': 16,
  'otLosses': 11,
  'placeName': {'default': 'Colorado'},
  'pointPctg': 0.737805,
  'points': 121,
  'regulationPlusOtWinPctg': 0.621951,
  'regulationPlusOtWins': 51,
  'regulationWinPctg': 0.585366,
  'regulationWins': 48,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 50,
  'roadGoalsAgainst': 95,
  'roadGoalsFor': 145,
  'roadLosses': 7,
  'roadOtLosses': 5,
  'roadPoints': 63,
  'roadRegulationPlusOtWins': 26,
  'roadRegulationWins': 23,
  'roadTies': 0,
  'roadWins': 29,
  'seasonId': 20252026,
  'shootoutLosses': 6,
  'shootoutWins': 4,
  'streakCode': 'W',
  'streakCount': 3,
  'teamName': {'default': 'Colorado Avalanche', 'fr': 'Avalanche du Colorado'},
  'teamCommonName': {'default': 'Avalanche'},
  'teamAbbrev': {'default': 'COL'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/COL_dark.svg',
  'ties': 0,
  'waiversSequence': 32,
  'wildcardSequence': 0,
  'winPctg': 0.670732,
  'wins': 55},
 {'clinchIndicator': 'z',
  'conferenceAbbrev': 'E',
  'conferenceHomeSequence': 1,
  'conferenceL10Sequence': 2,
  'conferenceName': 'Eastern',
  'conferenceRoadSequence': 3,
  'conferenceSequence': 1,
  'date': '2026-04-17',
  'divisionAbbrev': 'M',
  'divisionHomeSequence': 1,
  'divisionL10Sequence': 2,
  'divisionName': 'Metropolitan',
  'divisionRoadSequence': 1,
  'divisionSequence': 1,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 56,
  'goalDifferentialPctg': 0.682927,
  'goalAgainst': 240,
  'goalFor': 296,
  'goalsForPctg': 3.609756,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 35,
  'homeGoalsAgainst': 126,
  'homeGoalsFor': 161,
  'homeLosses': 10,
  'homeOtLosses': 2,
  'homePoints': 60,
  'homeRegulationPlusOtWins': 27,
  'homeRegulationWins': 20,
  'homeTies': 0,
  'homeWins': 29,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 12,
  'l10GoalsAgainst': 27,
  'l10GoalsFor': 39,
  'l10Losses': 2,
  'l10OtLosses': 1,
  'l10Points': 15,
  'l10RegulationPlusOtWins': 7,
  'l10RegulationWins': 6,
  'l10Ties': 0,
  'l10Wins': 7,
  'leagueHomeSequence': 1,
  'leagueL10Sequence': 3,
  'leagueRoadSequence': 5,
  'leagueSequence': 2,
  'losses': 22,
  'otLosses': 7,
  'placeName': {'default': 'Carolina', 'fr': 'Caroline'},
  'pointPctg': 0.689024,
  'points': 113,
  'regulationPlusOtWinPctg': 0.585366,
  'regulationPlusOtWins': 48,
  'regulationWinPctg': 0.47561,
  'regulationWins': 39,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 21,
  'roadGoalsAgainst': 114,
  'roadGoalsFor': 135,
  'roadLosses': 12,
  'roadOtLosses': 5,
  'roadPoints': 53,
  'roadRegulationPlusOtWins': 21,
  'roadRegulationWins': 19,
  'roadTies': 0,
  'roadWins': 24,
  'seasonId': 20252026,
  'shootoutLosses': 4,
  'shootoutWins': 5,
  'streakCode': 'W',
  'streakCount': 1,
  'teamName': {'default': 'Carolina Hurricanes',
   'fr': 'Hurricanes de la Caroline'},
  'teamCommonName': {'default': 'Hurricanes'},
  'teamAbbrev': {'default': 'CAR'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/CAR_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/CAR_dark.svg',
  'ties': 0,
  'waiversSequence': 31,
  'wildcardSequence': 0,
  'winPctg': 0.646341,
  'wins': 53},
 {'clinchIndicator': 'x',
  'conferenceAbbrev': 'W',
  'conferenceHomeSequence': 2,
  'conferenceL10Sequence': 3,
  'conferenceName': 'Western',
  'conferenceRoadSequence': 2,
  'conferenceSequence': 2,
  'date': '2026-04-17',
  'divisionAbbrev': 'C',
  'divisionHomeSequence': 2,
  'divisionL10Sequence': 2,
  'divisionName': 'Central',
  'divisionRoadSequence': 2,
  'divisionSequence': 2,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 53,
  'goalDifferentialPctg': 0.646341,
  'goalAgainst': 226,
  'goalFor': 279,
  'goalsForPctg': 3.402439,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 23,
  'homeGoalsAgainst': 112,
  'homeGoalsFor': 135,
  'homeLosses': 11,
  'homeOtLosses': 4,
  'homePoints': 56,
  'homeRegulationPlusOtWins': 24,
  'homeRegulationWins': 19,
  'homeTies': 0,
  'homeWins': 26,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 6,
  'l10GoalsAgainst': 28,
  'l10GoalsFor': 34,
  'l10Losses': 2,
  'l10OtLosses': 1,
  'l10Points': 15,
  'l10RegulationPlusOtWins': 6,
  'l10RegulationWins': 5,
  'l10Ties': 0,
  'l10Wins': 7,
  'leagueHomeSequence': 5,
  'leagueL10Sequence': 5,
  'leagueRoadSequence': 2,
  'leagueSequence': 3,
  'losses': 20,
  'otLosses': 12,
  'placeName': {'default': 'Dallas'},
  'pointPctg': 0.682927,
  'points': 112,
  'regulationPlusOtWinPctg': 0.536585,
  'regulationPlusOtWins': 44,
  'regulationWinPctg': 0.463415,
  'regulationWins': 38,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 30,
  'roadGoalsAgainst': 114,
  'roadGoalsFor': 144,
  'roadLosses': 9,
  'roadOtLosses': 8,
  'roadPoints': 56,
  'roadRegulationPlusOtWins': 20,
  'roadRegulationWins': 19,
  'roadTies': 0,
  'roadWins': 24,
  'seasonId': 20252026,
  'shootoutLosses': 4,
  'shootoutWins': 6,
  'streakCode': 'W',
  'streakCount': 5,
  'teamName': {'default': 'Dallas Stars', 'fr': 'Stars de Dallas'},
  'teamCommonName': {'default': 'Stars'},
  'teamAbbrev': {'default': 'DAL'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/DAL_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/DAL_dark.svg',
  'ties': 0,
  'waiversSequence': 30,
  'wildcardSequence': 0,
  'winPctg': 0.609756,
  'wins': 50},
 {'clinchIndicator': 'y',
  'conferenceAbbrev': 'E',
  'conferenceHomeSequence': 3,
  'conferenceL10Sequence': 6,
  'conferenceName': 'Eastern',
  'conferenceRoadSequence': 4,
  'conferenceSequence': 2,
  'date': '2026-04-17',
  'divisionAbbrev': 'A',
  'divisionHomeSequence': 2,
  'divisionL10Sequence': 3,
  'divisionName': 'Atlantic',
  'divisionRoadSequence': 3,
  'divisionSequence': 1,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 47,
  'goalDifferentialPctg': 0.573171,
  'goalAgainst': 241,
  'goalFor': 288,
  'goalsForPctg': 3.512195,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 30,
  'homeGoalsAgainst': 119,
  'homeGoalsFor': 149,
  'homeLosses': 10,
  'homeOtLosses': 5,
  'homePoints': 57,
  'homeRegulationPlusOtWins': 22,
  'homeRegulationWins': 22,
  'homeTies': 0,
  'homeWins': 26,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 4,
  'l10GoalsAgainst': 30,
  'l10GoalsFor': 34,
  'l10Losses': 3,
  'l10OtLosses': 1,
  'l10Points': 13,
  'l10RegulationPlusOtWins': 5,
  'l10RegulationWins': 5,
  'l10Ties': 0,
  'l10Wins': 6,
  'leagueHomeSequence': 4,
  'leagueL10Sequence': 12,
  'leagueRoadSequence': 6,
  'leagueSequence': 4,
  'losses': 23,
  'otLosses': 9,
  'placeName': {'default': 'Buffalo'},
  'pointPctg': 0.664634,
  'points': 109,
  'regulationPlusOtWinPctg': 0.54878,
  'regulationPlusOtWins': 45,
  'regulationWinPctg': 0.512195,
  'regulationWins': 42,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 17,
  'roadGoalsAgainst': 122,
  'roadGoalsFor': 139,
  'roadLosses': 13,
  'roadOtLosses': 4,
  'roadPoints': 52,
  'roadRegulationPlusOtWins': 23,
  'roadRegulationWins': 20,
  'roadTies': 0,
  'roadWins': 24,
  'seasonId': 20252026,
  'shootoutLosses': 1,
  'shootoutWins': 5,
  'streakCode': 'OT',
  'streakCount': 1,
  'teamName': {'default': 'Buffalo Sabres', 'fr': 'Sabres de Buffalo'},
  'teamCommonName': {'default': 'Sabres'},
  'teamAbbrev': {'default': 'BUF'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/BUF_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/BUF_dark.svg',
  'ties': 0,
  'waiversSequence': 29,
  'wildcardSequence': 0,
  'winPctg': 0.609756,
  'wins': 50},
 {'clinchIndicator': 'x',
  'conferenceAbbrev': 'E',
  'conferenceHomeSequence': 5,
  'conferenceL10Sequence': 12,
  'conferenceName': 'Eastern',
  'conferenceRoadSequence': 2,
  'conferenceSequence': 3,
  'date': '2026-04-17',
  'divisionAbbrev': 'A',
  'divisionHomeSequence': 3,
  'divisionL10Sequence': 6,
  'divisionName': 'Atlantic',
  'divisionRoadSequence': 2,
  'divisionSequence': 2,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 59,
  'goalDifferentialPctg': 0.719512,
  'goalAgainst': 231,
  'goalFor': 290,
  'goalsForPctg': 3.536585,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 22,
  'homeGoalsAgainst': 115,
  'homeGoalsFor': 137,
  'homeLosses': 14,
  'homeOtLosses': 1,
  'homePoints': 53,
  'homeRegulationPlusOtWins': 24,
  'homeRegulationWins': 19,
  'homeTies': 0,
  'homeWins': 26,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': -4,
  'l10GoalsAgainst': 30,
  'l10GoalsFor': 26,
  'l10Losses': 5,
  'l10OtLosses': 0,
  'l10Points': 10,
  'l10RegulationPlusOtWins': 5,
  'l10RegulationWins': 4,
  'l10Ties': 0,
  'l10Wins': 5,
  'leagueHomeSequence': 8,
  'leagueL10Sequence': 21,
  'leagueRoadSequence': 4,
  'leagueSequence': 5,
  'losses': 26,
  'otLosses': 6,
  'placeName': {'default': 'Tampa Bay'},
  'pointPctg': 0.646341,
  'points': 106,
  'regulationPlusOtWinPctg': 0.560976,
  'regulationPlusOtWins': 46,
  'regulationWinPctg': 0.487805,
  'regulationWins': 40,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 37,
  'roadGoalsAgainst': 116,
  'roadGoalsFor': 153,
  'roadLosses': 12,
  'roadOtLosses': 5,
  'roadPoints': 53,
  'roadRegulationPlusOtWins': 22,
  'roadRegulationWins': 21,
  'roadTies': 0,
  'roadWins': 24,
  'seasonId': 20252026,
  'shootoutLosses': 2,
  'shootoutWins': 4,
  'streakCode': 'L',
  'streakCount': 1,
  'teamName': {'default': 'Tampa Bay Lightning',
   'fr': 'Lightning de Tampa Bay'},
  'teamCommonName': {'default': 'Lightning'},
  'teamAbbrev': {'default': 'TBL'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/TBL_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/TBL_dark.svg',
  'ties': 0,
  'waiversSequence': 28,
  'wildcardSequence': 0,
  'winPctg': 0.609756,
  'wins': 50},
 {'clinchIndicator': 'x',
  'conferenceAbbrev': 'E',
  'conferenceHomeSequence': 7,
  'conferenceL10Sequence': 3,
  'conferenceName': 'Eastern',
  'conferenceRoadSequence': 1,
  'conferenceSequence': 4,
  'date': '2026-04-17',
  'divisionAbbrev': 'A',
  'divisionHomeSequence': 5,
  'divisionL10Sequence': 1,
  'divisionName': 'Atlantic',
  'divisionRoadSequence': 1,
  'divisionSequence': 3,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 27,
  'goalDifferentialPctg': 0.329268,
  'goalAgainst': 256,
  'goalFor': 283,
  'goalsForPctg': 3.45122,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 10,
  'homeGoalsAgainst': 127,
  'homeGoalsFor': 137,
  'homeLosses': 15,
  'homeOtLosses': 2,
  'homePoints': 50,
  'homeRegulationPlusOtWins': 22,
  'homeRegulationWins': 17,
  'homeTies': 0,
  'homeWins': 24,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 4,
  'l10GoalsAgainst': 24,
  'l10GoalsFor': 28,
  'l10Losses': 3,
  'l10OtLosses': 0,
  'l10Points': 14,
  'l10RegulationPlusOtWins': 5,
  'l10RegulationWins': 5,
  'l10Ties': 0,
  'l10Wins': 7,
  'leagueHomeSequence': 12,
  'leagueL10Sequence': 7,
  'leagueRoadSequence': 3,
  'leagueSequence': 6,
  'losses': 24,
  'otLosses': 10,
  'placeName': {'default': 'Montréal'},
  'pointPctg': 0.646341,
  'points': 106,
  'regulationPlusOtWinPctg': 0.536585,
  'regulationPlusOtWins': 44,
  'regulationWinPctg': 0.414634,
  'regulationWins': 34,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 17,
  'roadGoalsAgainst': 129,
  'roadGoalsFor': 146,
  'roadLosses': 9,
  'roadOtLosses': 8,
  'roadPoints': 56,
  'roadRegulationPlusOtWins': 22,
  'roadRegulationWins': 17,
  'roadTies': 0,
  'roadWins': 24,
  'seasonId': 20252026,
  'shootoutLosses': 5,
  'shootoutWins': 4,
  'streakCode': 'L',
  'streakCount': 1,
  'teamName': {'default': 'Montréal Canadiens', 'fr': 'Canadiens de Montréal'},
  'teamCommonName': {'default': 'Canadiens'},
  'teamAbbrev': {'default': 'MTL'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MTL_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/MTL_dark.svg',
  'ties': 0,
  'waiversSequence': 27,
  'wildcardSequence': 0,
  'winPctg': 0.585366,
  'wins': 48},
 {'clinchIndicator': 'x',
  'conferenceAbbrev': 'W',
  'conferenceHomeSequence': 3,
  'conferenceL10Sequence': 7,
  'conferenceName': 'Western',
  'conferenceRoadSequence': 4,
  'conferenceSequence': 3,
  'date': '2026-04-17',
  'divisionAbbrev': 'C',
  'divisionHomeSequence': 3,
  'divisionL10Sequence': 4,
  'divisionName': 'Central',
  'divisionRoadSequence': 3,
  'divisionSequence': 3,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 32,
  'goalDifferentialPctg': 0.390244,
  'goalAgainst': 240,
  'goalFor': 272,
  'goalsForPctg': 3.317073,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 15,
  'homeGoalsAgainst': 115,
  'homeGoalsFor': 130,
  'homeLosses': 10,
  'homeOtLosses': 8,
  'homePoints': 54,
  'homeRegulationPlusOtWins': 19,
  'homeRegulationWins': 14,
  'homeTies': 0,
  'homeWins': 23,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 4,
  'l10GoalsAgainst': 32,
  'l10GoalsFor': 36,
  'l10Losses': 4,
  'l10OtLosses': 0,
  'l10Points': 12,
  'l10RegulationPlusOtWins': 6,
  'l10RegulationWins': 6,
  'l10Ties': 0,
  'l10Wins': 6,
  'leagueHomeSequence': 7,
  'leagueL10Sequence': 14,
  'leagueRoadSequence': 9,
  'leagueSequence': 7,
  'losses': 24,
  'otLosses': 12,
  'placeName': {'default': 'Minnesota'},
  'pointPctg': 0.634146,
  'points': 104,
  'regulationPlusOtWinPctg': 0.512195,
  'regulationPlusOtWins': 42,
  'regulationWinPctg': 0.378049,
  'regulationWins': 31,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 17,
  'roadGoalsAgainst': 125,
  'roadGoalsFor': 142,
  'roadLosses': 14,
  'roadOtLosses': 4,
  'roadPoints': 50,
  'roadRegulationPlusOtWins': 23,
  'roadRegulationWins': 17,
  'roadTies': 0,
  'roadWins': 23,
  'seasonId': 20252026,
  'shootoutLosses': 5,
  'shootoutWins': 4,
  'streakCode': 'W',
  'streakCount': 1,
  'teamName': {'default': 'Minnesota Wild', 'fr': 'Wild du Minnesota'},
  'teamCommonName': {'default': 'Wild'},
  'teamAbbrev': {'default': 'MIN'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MIN_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/MIN_dark.svg',
  'ties': 0,
  'waiversSequence': 26,
  'wildcardSequence': 0,
  'winPctg': 0.560976,
  'wins': 46},
 {'clinchIndicator': 'x',
  'conferenceAbbrev': 'E',
  'conferenceHomeSequence': 2,
  'conferenceL10Sequence': 8,
  'conferenceName': 'Eastern',
  'conferenceRoadSequence': 13,
  'conferenceSequence': 5,
  'date': '2026-04-17',
  'divisionAbbrev': 'A',
  'divisionHomeSequence': 1,
  'divisionL10Sequence': 4,
  'divisionName': 'Atlantic',
  'divisionRoadSequence': 6,
  'divisionSequence': 4,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 22,
  'goalDifferentialPctg': 0.268293,
  'goalAgainst': 250,
  'goalFor': 272,
  'goalsForPctg': 3.317073,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 40,
  'homeGoalsAgainst': 105,
  'homeGoalsFor': 145,
  'homeLosses': 11,
  'homeOtLosses': 1,
  'homePoints': 59,
  'homeRegulationPlusOtWins': 28,
  'homeRegulationWins': 23,
  'homeTies': 0,
  'homeWins': 29,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 6,
  'l10GoalsAgainst': 26,
  'l10GoalsFor': 32,
  'l10Losses': 3,
  'l10OtLosses': 2,
  'l10Points': 12,
  'l10RegulationPlusOtWins': 4,
  'l10RegulationWins': 4,
  'l10Ties': 0,
  'l10Wins': 5,
  'leagueHomeSequence': 2,
  'leagueL10Sequence': 16,
  'leagueRoadSequence': 21,
  'leagueSequence': 8,
  'losses': 27,
  'otLosses': 10,
  'placeName': {'default': 'Boston'},
  'pointPctg': 0.609756,
  'points': 100,
  'regulationPlusOtWinPctg': 0.5,
  'regulationPlusOtWins': 41,
  'regulationWinPctg': 0.402439,
  'regulationWins': 33,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': -18,
  'roadGoalsAgainst': 145,
  'roadGoalsFor': 127,
  'roadLosses': 16,
  'roadOtLosses': 9,
  'roadPoints': 41,
  'roadRegulationPlusOtWins': 13,
  'roadRegulationWins': 10,
  'roadTies': 0,
  'roadWins': 16,
  'seasonId': 20252026,
  'shootoutLosses': 3,
  'shootoutWins': 4,
  'streakCode': 'W',
  'streakCount': 2,
  'teamName': {'default': 'Boston Bruins', 'fr': 'Bruins de Boston'},
  'teamCommonName': {'default': 'Bruins'},
  'teamAbbrev': {'default': 'BOS'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/BOS_light.svg?season=20252026',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/BOS_dark.svg?season=20252026',
  'ties': 0,
  'waiversSequence': 25,
  'wildcardSequence': 1,
  'winPctg': 0.54878,
  'wins': 45},
 {'clinchIndicator': 'x',
  'conferenceAbbrev': 'E',
  'conferenceHomeSequence': 6,
  'conferenceL10Sequence': 5,
  'conferenceName': 'Eastern',
  'conferenceRoadSequence': 7,
  'conferenceSequence': 6,
  'date': '2026-04-17',
  'divisionAbbrev': 'A',
  'divisionHomeSequence': 4,
  'divisionL10Sequence': 2,
  'divisionName': 'Atlantic',
  'divisionRoadSequence': 4,
  'divisionSequence': 5,
  'gameTypeId': 2,
  'gamesPlayed': 82,
  'goalDifferential': 32,
  'goalDifferentialPctg': 0.390244,
  'goalAgainst': 246,
  'goalFor': 278,
  'goalsForPctg': 3.390244,
  'homeGamesPlayed': 41,
  'homeGoalDifferential': 31,
  'homeGoalsAgainst': 108,
  'homeGoalsFor': 139,
  'homeLosses': 12,
  'homeOtLosses': 6,
  'homePoints': 52,
  'homeRegulationPlusOtWins': 21,
  'homeRegulationWins': 21,
  'homeTies': 0,
  'homeWins': 23,
  'l10GamesPlayed': 10,
  'l10GoalDifferential': 10,
  'l10GoalsAgainst': 26,
  'l10GoalsFor': 36,
  'l10Losses': 3,
  'l10OtLosses': 1,
  'l10Points': 13,
  'l10RegulationPlusOtWins': 6,
  'l10RegulationWins': 6,
  'l10Ties': 0,
  'l10Wins': 6,
  'leagueHomeSequence': 9,
  'leagueL10Sequence': 10,
  'leagueRoadSequence': 11,
  'leagueSequence': 9,
  'losses': 27,
  'otLosses': 11,
  'placeName': {'default': 'Ottawa'},
  'pointPctg': 0.603659,
  'points': 99,
  'regulationPlusOtWinPctg': 0.5,
  'regulationPlusOtWins': 41,
  'regulationWinPctg': 0.463415,
  'regulationWins': 38,
  'roadGamesPlayed': 41,
  'roadGoalDifferential': 1,
  'roadGoalsAgainst': 138,
  'roadGoalsFor': 139,
  'roadLosses': 15,
  'roadOtLosses': 5,
  'roadPoints': 47,
  'roadRegulationPlusOtWins': 20,
  'roadRegulationWins': 17,
  'roadTies': 0,
  'roadWins': 21,
  'seasonId': 20252026,
  'shootoutLosses': 1,
  'shootoutWins': 3,
  'streakCode': 'W',
  'streakCount': 1,
  'teamName': {'default': 'Ottawa Senators', 'fr': "Sénateurs d'Ottawa"},
  'teamCommonName': {'default': 'Senators', 'fr': 'Sénateurs'},
  'teamAbbrev': {'default': 'OTT'},
  'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/OTT_light.svg',
  'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/OTT_dark.svg',
  'ties': 0,
  'waiversSequence': 24,
  'wildcardSequence': 2,
  'winPctg': 0.536585,
  'wins': 44},
 {'clinchIndicator': 'x',
  'conferenceAbbrev': 'E',
  'conferenceHomeSequence': 10,
  'conferenceL10Sequence': 11,
  'conferenceName': 'Eastern',
  'conferenceRoadSequence': 5,
  'conferenceSequence': 7,
  'date': '2026-04-17',
  'divisionAbbrev': 'M',

In [133]:
len(data['standings'])

32

# Extract the fields required

In [134]:
for team in data['standings']:
    print(team)
    break

{'clinchIndicator': 'p', 'conferenceAbbrev': 'W', 'conferenceHomeSequence': 1, 'conferenceL10Sequence': 2, 'conferenceName': 'Western', 'conferenceRoadSequence': 1, 'conferenceSequence': 1, 'date': '2026-04-17', 'divisionAbbrev': 'C', 'divisionHomeSequence': 1, 'divisionL10Sequence': 1, 'divisionName': 'Central', 'divisionRoadSequence': 1, 'divisionSequence': 1, 'gameTypeId': 2, 'gamesPlayed': 82, 'goalDifferential': 99, 'goalDifferentialPctg': 1.207317, 'goalAgainst': 203, 'goalFor': 302, 'goalsForPctg': 3.682927, 'homeGamesPlayed': 41, 'homeGoalDifferential': 49, 'homeGoalsAgainst': 108, 'homeGoalsFor': 157, 'homeLosses': 9, 'homeOtLosses': 6, 'homePoints': 58, 'homeRegulationPlusOtWins': 25, 'homeRegulationWins': 25, 'homeTies': 0, 'homeWins': 26, 'l10GamesPlayed': 10, 'l10GoalDifferential': 14, 'l10GoalsAgainst': 20, 'l10GoalsFor': 34, 'l10Losses': 2, 'l10OtLosses': 1, 'l10Points': 15, 'l10RegulationPlusOtWins': 6, 'l10RegulationWins': 6, 'l10Ties': 0, 'l10Wins': 7, 'leagueHomeSequence': 3, 'leagueL10Sequence': 4, 'leagueRoadSequence': 1, 'leagueSequence': 1, 'losses': 16, 'otLosses': 11, 'placeName': {'default': 'Colorado'}, 'pointPctg': 0.737805, 'points': 121, 'regulationPlusOtWinPctg': 0.621951, 'regulationPlusOtWins': 51, 'regulationWinPctg': 0.585366, 'regulationWins': 48, 'roadGamesPlayed': 41, 'roadGoalDifferential': 50, 'roadGoalsAgainst': 95, 'roadGoalsFor': 145, 'roadLosses': 7, 'roadOtLosses': 5, 'roadPoints': 63, 'roadRegulationPlusOtWins': 26, 'roadRegulationWins': 23, 'roadTies': 0, 'roadWins': 29, 'seasonId': 20252026, 'shootoutLosses': 6, 'shootoutWins': 4, 'streakCode': 'W', 'streakCount': 3, 'teamName': {'default': 'Colorado Avalanche', 'fr': 'Avalanche du Colorado'}, 'teamCommonName': {'default': 'Avalanche'}, 'teamAbbrev': {'default': 'COL'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg', 'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/COL_dark.svg', 'ties': 0, 'waiversSequence': 32, 'wildcardSequence': 0, 'winPctg': 0.670732, 'wins': 55}

In [135]:
for team in data["standings"][:5]:
    print(
        team.get("teamName", {}).get("default"),
        "Wins:", team.get("wins"),
        "Losses:", team.get("losses"),
        "Points:", team.get("points")
    )

Colorado Avalanche Wins: 55 Losses: 16 Points: 121
Carolina Hurricanes Wins: 53 Losses: 22 Points: 113
Dallas Stars Wins: 50 Losses: 20 Points: 112
Buffalo Sabres Wins: 50 Losses: 23 Points: 109
Tampa Bay Lightning Wins: 50 Losses: 26 Points: 106

In [136]:
data["standings"][0].keys()

dict_keys(['clinchIndicator', 'conferenceAbbrev', 'conferenceHomeSequence', 'conferenceL10Sequence', 'conferenceName', 'conferenceRoadSequence', 'conferenceSequence', 'date', 'divisionAbbrev', 'divisionHomeSequence', 'divisionL10Sequence', 'divisionName', 'divisionRoadSequence', 'divisionSequence', 'gameTypeId', 'gamesPlayed', 'goalDifferential', 'goalDifferentialPctg', 'goalAgainst', 'goalFor', 'goalsForPctg', 'homeGamesPlayed', 'homeGoalDifferential', 'homeGoalsAgainst', 'homeGoalsFor', 'homeLosses', 'homeOtLosses', 'homePoints', 'homeRegulationPlusOtWins', 'homeRegulationWins', 'homeTies', 'homeWins', 'l10GamesPlayed', 'l10GoalDifferential', 'l10GoalsAgainst', 'l10GoalsFor', 'l10Losses', 'l10OtLosses', 'l10Points', 'l10RegulationPlusOtWins', 'l10RegulationWins', 'l10Ties', 'l10Wins', 'leagueHomeSequence', 'leagueL10Sequence', 'leagueRoadSequence', 'leagueSequence', 'losses', 'otLosses', 'placeName', 'pointPctg', 'points', 'regulationPlusOtWinPctg', 'regulationPlusOtWins', 'regulationWinPctg', 'regulationWins', 'roadGamesPlayed', 'roadGoalDifferential', 'roadGoalsAgainst', 'roadGoalsFor', 'roadLosses', 'roadOtLosses', 'roadPoints', 'roadRegulationPlusOtWins', 'roadRegulationWins', 'roadTies', 'roadWins', 'seasonId', 'shootoutLosses', 'shootoutWins', 'streakCode', 'streakCount', 'teamName', 'teamCommonName', 'teamAbbrev', 'teamLogo', 'teamLogoDark', 'ties', 'waiversSequence', 'wildcardSequence', 'winPctg', 'wins'])

In [137]:
! pip install pandas

Requirement already satisfied: pandas in /Users/rahulshrivastav/Desktop/NHL Analytics Hub/venv/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in /Users/rahulshrivastav/Desktop/NHL Analytics Hub/venv/lib/python3.14/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rahulshrivastav/Desktop/NHL Analytics Hub/venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/rahulshrivastav/Desktop/NHL Analytics Hub/venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [138]:
import pandas as pd

standings_data = []

for team in data["standings"]:
    standings_data.append({
        "team": team.get("teamName", {}).get("default"),
        "wins": team.get("wins"),
        "losses": team.get("losses"),
        "ot_losses": team.get("otLosses"),
        "points": team.get("points"),
        "goals_for": team.get("goalFor"),
        "goals_against": team.get("goalAgainst"),
        "games_played": team.get("gamesPlayed")
    })

df = pd.DataFrame(standings_data)

df.head()

,team,wins,losses,ot_losses,points,goals_for,goals_against,games_played
0,Colorado Avalanche,55,16,11,121,302,203,82
1,Carolina Hurricanes,53,22,7,113,296,240,82
2,Dallas Stars,50,20,12,112,279,226,82
3,Buffalo Sabres,50,23,9,109,288,241,82
4,Tampa Bay Lightning,50,26,6,106,290,231,82

In [139]:
df.shape

(32, 8)

In [140]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   team           32 non-null     str
 1   wins           32 non-null     int64
 2   losses         32 non-null     int64
 3   ot_losses      32 non-null     int64
 4   points         32 non-null     int64
 5   goals_for      32 non-null     int64
 6   goals_against  32 non-null     int64
 7   games_played   32 non-null     int64
dtypes: int64(7), str(1)
memory usage: 2.1 KB

In [141]:
df.isnull().sum()

team             0
wins             0
losses           0
ot_losses        0
points           0
goals_for        0
goals_against    0
games_played     0
dtype: int64

In [142]:
df.to_csv("../data/raw/standings.csv", index=False)

print("Standings data saved successfully!")

Standings data saved successfully!

In [143]:
pd.read_csv("../data/raw/standings.csv").head()

,team,wins,losses,ot_losses,points,goals_for,goals_against,games_played
0,Colorado Avalanche,55,16,11,121,302,203,82
1,Carolina Hurricanes,53,22,7,113,296,240,82
2,Dallas Stars,50,20,12,112,279,226,82
3,Buffalo Sabres,50,23,9,109,288,241,82
4,Tampa Bay Lightning,50,26,6,106,290,231,82

In [144]:
# Check for missing values in each column of the dataset
df.isnull().sum()

team             0
wins             0
losses           0
ot_losses        0
points           0
goals_for        0
goals_against    0
games_played     0
dtype: int64

In [145]:
# Check whether the dataset contains any duplicate rows
df.duplicated().sum()

np.int64(0)

In [146]:
# Generate summary statistics to understand the numerical columns
df.describe()

,wins,losses,ot_losses,points,goals_for,goals_against,games_played
count,32.000000,32.000000,32.00000,32.000000,32.000000,32.000000,32.0
mean,41.000000,30.812500,10.18750,92.187500,256.406250,256.406250,82.0
std,6.810807,6.874157,3.69339,13.177296,26.143351,22.183777,0.0
min,25.000000,16.000000,3.00000,58.000000,212.000000,203.000000,82.0
25%,36.500000,26.000000,8.00000,85.500000,232.500000,242.500000,82.0
50%,41.000000,30.500000,10.00000,92.000000,253.000000,253.500000,82.0
75%,44.250000,35.250000,12.00000,99.250000,278.250000,268.250000,82.0
max,55.000000,49.000000,20.00000,121.000000,302.000000,316.000000,82.0

In [147]:
# Display all column names to understand the dataset structure
df.columns

Index(['team', 'wins', 'losses', 'ot_losses', 'points', 'goals_for',
       'goals_against', 'games_played'],
      dtype='str')

In [148]:
df.dtypes

team               str
wins             int64
losses           int64
ot_losses        int64
points           int64
goals_for        int64
goals_against    int64
games_played     int64
dtype: object

In [149]:
# Check the number of unique teams in the dataset
df['team'].nunique()

32

In [150]:
df.sort_values(by='points', ascending=False)

,team,wins,losses,ot_losses,points,goals_for,goals_against,games_played
0,Colorado Avalanche,55,16,11,121,302,203,82
1,Carolina Hurricanes,53,22,7,113,296,240,82
2,Dallas Stars,50,20,12,112,279,226,82
3,Buffalo Sabres,50,23,9,109,288,241,82
4,Tampa Bay Lightning,50,26,6,106,290,231,82
5,Montréal Canadiens,48,24,10,106,283,256,82
6,Minnesota Wild,46,24,12,104,272,240,82
7,Boston Bruins,45,27,10,100,272,250,82
8,Ottawa Senators,44,27,11,99,278,246,82
9,Pittsburgh Penguins,41,25,16,98,293,268,82
10,Philadelphia Flyers,43,27,12,98,250,243,82
11,Washington Capitals,43,30,9,95,263,244,82
12,Vegas Golden Knights,39,26,17,95,265,250,82
13,Edmonton Oilers,41,30,11,93,282,269,82
17,Anaheim Ducks,43,33,6,92,273,288,82
16,Columbus Blue Jackets,40,30,12,92,253,253,82
15,Detroit Red Wings,41,31,10,92,241,258,82
14,Utah Mammoth,43,33,6,92,268,240,82
18,New York Islanders,43,34,5,91,233,241,82
19,Los Angeles Kings,35,27,20,90,225,247,82
20,New Jersey Devils,42,37,3,87,230,254,82
21,St. Louis Blues,37,33,12,86,231,258,82
22,Nashville Predators,38,34,10,86,247,269,82
23,San Jose Sharks,39,35,8,86,251,292,82
24,Florida Panthers,40,38,4,84,251,276,82
25,Winnipeg Jets,35,35,12,82,231,260,82
26,Seattle Kraken,34,37,11,79,226,263,82
27,Toronto Maple Leafs,32,36,14,78,253,299,82
28,Calgary Flames,34,39,9,77,212,259,82
29,New York Rangers,34,39,9,77,238,250,82
30,Chicago Blackhawks,29,39,14,72,213,275,82
31,Vancouver Canucks,25,49,8,58,216,316,82

In [151]:
# Select the top 5 teams based on their total points
top_5_teams = df.sort_values(by='points', ascending=False).head(5)

top_5_teams

,team,wins,losses,ot_losses,points,goals_for,goals_against,games_played
0,Colorado Avalanche,55,16,11,121,302,203,82
1,Carolina Hurricanes,53,22,7,113,296,240,82
2,Dallas Stars,50,20,12,112,279,226,82
3,Buffalo Sabres,50,23,9,109,288,241,82
4,Tampa Bay Lightning,50,26,6,106,290,231,82

In [152]:
# Find the team with the highest number of wins
top_wins_team = df.loc[df['wins'].idxmax()]
top_wins_team

team             Colorado Avalanche
wins                             55
losses                           16
ot_losses                        11
points                          121
goals_for                       302
goals_against                   203
games_played                     82
Name: 0, dtype: object

In [153]:
# Find the team that conceded the fewest goals during the season
best_defense_team = df.loc[df['goals_against'].idxmin()]

# Display the team with the fewest goals conceded
best_defense_team

team             Colorado Avalanche
wins                             55
losses                           16
ot_losses                        11
points                          121
goals_for                       302
goals_against                   203
games_played                     82
Name: 0, dtype: object

In [154]:
# Calculate the goal difference for each team
df['goal_difference'] = df['goals_for'] - df['goals_against']

df[['team', 'goal_difference']]

                     team  goal_difference
0      Colorado Avalanche               99
1     Carolina Hurricanes               56
2            Dallas Stars               53
3          Buffalo Sabres               47
4     Tampa Bay Lightning               59
5      Montréal Canadiens               27
6          Minnesota Wild               32
7           Boston Bruins               22
8         Ottawa Senators               32
9     Pittsburgh Penguins               25
10    Philadelphia Flyers                7
11    Washington Capitals               19
12   Vegas Golden Knights               15
13        Edmonton Oilers               13
14           Utah Mammoth               28
15      Detroit Red Wings              -17
16  Columbus Blue Jackets                0
17          Anaheim Ducks              -15
18     New York Islanders               -8
19      Los Angeles Kings              -22
20      New Jersey Devils              -24
21        St. Louis Blues              -27
22    Nashville Predators              -22
23        San Jose Sharks              -41
24       Florida Panthers              -25
25          Winnipeg Jets              -29
26         Seattle Kraken              -37
27    Toronto Maple Leafs              -46
28         Calgary Flames              -47
29       New York Rangers              -12
30     Chicago Blackhawks              -62
31      Vancouver Canucks             -100

In [155]:
# Find the team with the highest goal difference
best_goal_difference_team = df.loc[df['goal_difference'].idxmax()]

best_goal_difference_team

team               Colorado Avalanche
wins                               55
losses                             16
ot_losses                          11
points                            121
goals_for                         302
goals_against                     203
games_played                       82
goal_difference                    99
Name: 0, dtype: object

In [156]:
# Calculate the win percentage for each team
df['win_percentage'] = (df['wins'] / df['games_played']) * 100

df[['team', 'wins', 'games_played', 'win_percentage']]

                     team  wins  games_played  win_percentage
0      Colorado Avalanche    55            82       67.073171
1     Carolina Hurricanes    53            82       64.634146
2            Dallas Stars    50            82       60.975610
3          Buffalo Sabres    50            82       60.975610
4     Tampa Bay Lightning    50            82       60.975610
5      Montréal Canadiens    48            82       58.536585
6          Minnesota Wild    46            82       56.097561
7           Boston Bruins    45            82       54.878049
8         Ottawa Senators    44            82       53.658537
9     Pittsburgh Penguins    41            82       50.000000
10    Philadelphia Flyers    43            82       52.439024
11    Washington Capitals    43            82       52.439024
12   Vegas Golden Knights    39            82       47.560976
13        Edmonton Oilers    41            82       50.000000
14           Utah Mammoth    43            82       52.439024
15      Detroit Red Wings    41            82       50.000000
16  Columbus Blue Jackets    40            82       48.780488
17          Anaheim Ducks    43            82       52.439024
18     New York Islanders    43            82       52.439024
19      Los Angeles Kings    35            82       42.682927
20      New Jersey Devils    42            82       51.219512
21        St. Louis Blues    37            82       45.121951
22    Nashville Predators    38            82       46.341463
23        San Jose Sharks    39            82       47.560976
24       Florida Panthers    40            82       48.780488
25          Winnipeg Jets    35            82       42.682927
26         Seattle Kraken    34            82       41.463415
27    Toronto Maple Leafs    32            82       39.024390
28         Calgary Flames    34            82       41.463415
29       New York Rangers    34            82       41.463415
30     Chicago Blackhawks    29            82       35.365854
31      Vancouver Canucks    25            82       30.487805

In [157]:
# Find the team with the highest win percentage
best_win_percentage_team = df.loc[df['win_percentage'].idxmax()]

best_win_percentage_team

team               Colorado Avalanche
wins                               55
losses                             16
ot_losses                          11
points                            121
goals_for                         302
goals_against                     203
games_played                       82
goal_difference                    99
win_percentage              67.073171
Name: 0, dtype: object

In [158]:
# Calculate the average points earned per game for each team
df['points_per_game'] = df['points'] / df['games_played']

df[['team', 'points', 'games_played', 'points_per_game']]

                     team  points  games_played  points_per_game
0      Colorado Avalanche     121            82         1.475610
1     Carolina Hurricanes     113            82         1.378049
2            Dallas Stars     112            82         1.365854
3          Buffalo Sabres     109            82         1.329268
4     Tampa Bay Lightning     106            82         1.292683
5      Montréal Canadiens     106            82         1.292683
6          Minnesota Wild     104            82         1.268293
7           Boston Bruins     100            82         1.219512
8         Ottawa Senators      99            82         1.207317
9     Pittsburgh Penguins      98            82         1.195122
10    Philadelphia Flyers      98            82         1.195122
11    Washington Capitals      95            82         1.158537
12   Vegas Golden Knights      95            82         1.158537
13        Edmonton Oilers      93            82         1.134146
14           Utah Mammoth      92            82         1.121951
15      Detroit Red Wings      92            82         1.121951
16  Columbus Blue Jackets      92            82         1.121951
17          Anaheim Ducks      92            82         1.121951
18     New York Islanders      91            82         1.109756
19      Los Angeles Kings      90            82         1.097561
20      New Jersey Devils      87            82         1.060976
21        St. Louis Blues      86            82         1.048780
22    Nashville Predators      86            82         1.048780
23        San Jose Sharks      86            82         1.048780
24       Florida Panthers      84            82         1.024390
25          Winnipeg Jets      82            82         1.000000
26         Seattle Kraken      79            82         0.963415
27    Toronto Maple Leafs      78            82         0.951220
28         Calgary Flames      77            82         0.939024
29       New York Rangers      77            82         0.939024
30     Chicago Blackhawks      72            82         0.878049
31      Vancouver Canucks      58            82         0.707317

In [159]:
# Find the team with the highest points per game
best_points_per_game_team = df.loc[df['points_per_game'].idxmax()]

best_points_per_game_team

team               Colorado Avalanche
wins                               55
losses                             16
ot_losses                          11
points                            121
goals_for                         302
goals_against                     203
games_played                       82
goal_difference                    99
win_percentage              67.073171
points_per_game               1.47561
Name: 0, dtype: object

In [160]:
# Calculate the average goals conceded per game for each team
df['goals_against_per_game'] = df['goals_against'] / df['games_played']

df[['team', 'goals_against', 'games_played', 'goals_against_per_game']]

                     team  goals_against  games_played  goals_against_per_game
0      Colorado Avalanche            203            82                2.475610
1     Carolina Hurricanes            240            82                2.926829
2            Dallas Stars            226            82                2.756098
3          Buffalo Sabres            241            82                2.939024
4     Tampa Bay Lightning            231            82                2.817073
5      Montréal Canadiens            256            82                3.121951
6          Minnesota Wild            240            82                2.926829
7           Boston Bruins            250            82                3.048780
8         Ottawa Senators            246            82                3.000000
9     Pittsburgh Penguins            268            82                3.268293
10    Philadelphia Flyers            243            82                2.963415
11    Washington Capitals            244            82                2.975610
12   Vegas Golden Knights            250            82                3.048780
13        Edmonton Oilers            269            82                3.280488
14           Utah Mammoth            240            82                2.926829
15      Detroit Red Wings            258            82                3.146341
16  Columbus Blue Jackets            253            82                3.085366
17          Anaheim Ducks            288            82                3.512195
18     New York Islanders            241            82                2.939024
19      Los Angeles Kings            247            82                3.012195
20      New Jersey Devils            254            82                3.097561
21        St. Louis Blues            258            82                3.146341
22    Nashville Predators            269            82                3.280488
23        San Jose Sharks            292            82                3.560976
24       Florida Panthers            276            82                3.365854
25          Winnipeg Jets            260            82                3.170732
26         Seattle Kraken            263            82                3.207317
27    Toronto Maple Leafs            299            82                3.646341
28         Calgary Flames            259            82                3.158537
29       New York Rangers            250            82                3.048780
30     Chicago Blackhawks            275            82                3.353659
31      Vancouver Canucks            316            82                3.853659

In [161]:
# Find the team with the lowest goals conceded per game
best_defense_per_game = df.loc[df['goals_against_per_game'].idxmin()]

best_defense_per_game

team                      Colorado Avalanche
wins                                      55
losses                                    16
ot_losses                                 11
points                                   121
goals_for                                302
goals_against                            203
games_played                              82
goal_difference                           99
win_percentage                     67.073171
points_per_game                      1.47561
goals_against_per_game               2.47561
Name: 0, dtype: object

In [162]:
# Calculate the average goals scored per game for each team
df['goals_for_per_game'] = df['goals_for'] / df['games_played']

best_attack_team = df.loc[df['goals_for_per_game'].idxmax()] #highest goals scored per game

best_attack_team

team                      Colorado Avalanche
wins                                      55
losses                                    16
ot_losses                                 11
points                                   121
goals_for                                302
goals_against                            203
games_played                              82
goal_difference                           99
win_percentage                     67.073171
points_per_game                      1.47561
goals_against_per_game               2.47561
goals_for_per_game                  3.682927
Name: 0, dtype: object

In [163]:
# Compare goals scored and goals conceded by each team
df[['team', 'goals_for', 'goals_against', 'goal_difference']]

                     team  goals_for  goals_against  goal_difference
0      Colorado Avalanche        302            203               99
1     Carolina Hurricanes        296            240               56
2            Dallas Stars        279            226               53
3          Buffalo Sabres        288            241               47
4     Tampa Bay Lightning        290            231               59
5      Montréal Canadiens        283            256               27
6          Minnesota Wild        272            240               32
7           Boston Bruins        272            250               22
8         Ottawa Senators        278            246               32
9     Pittsburgh Penguins        293            268               25
10    Philadelphia Flyers        250            243                7
11    Washington Capitals        263            244               19
12   Vegas Golden Knights        265            250               15
13        Edmonton Oilers        282            269               13
14           Utah Mammoth        268            240               28
15      Detroit Red Wings        241            258              -17
16  Columbus Blue Jackets        253            253                0
17          Anaheim Ducks        273            288              -15
18     New York Islanders        233            241               -8
19      Los Angeles Kings        225            247              -22
20      New Jersey Devils        230            254              -24
21        St. Louis Blues        231            258              -27
22    Nashville Predators        247            269              -22
23        San Jose Sharks        251            292              -41
24       Florida Panthers        251            276              -25
25          Winnipeg Jets        231            260              -29
26         Seattle Kraken        226            263              -37
27    Toronto Maple Leafs        253            299              -46
28         Calgary Flames        212            259              -47
29       New York Rangers        238            250              -12
30     Chicago Blackhawks        213            275              -62
31      Vancouver Canucks        216            316             -100

In [164]:
# Sort teams by goal difference to identify the strongest and weakest overall performance
df.sort_values(by='goal_difference', ascending=False)[
    ['team', 'goals_for', 'goals_against', 'goal_difference']
]

                     team  goals_for  goals_against  goal_difference
0      Colorado Avalanche        302            203               99
4     Tampa Bay Lightning        290            231               59
1     Carolina Hurricanes        296            240               56
2            Dallas Stars        279            226               53
3          Buffalo Sabres        288            241               47
6          Minnesota Wild        272            240               32
8         Ottawa Senators        278            246               32
14           Utah Mammoth        268            240               28
5      Montréal Canadiens        283            256               27
9     Pittsburgh Penguins        293            268               25
7           Boston Bruins        272            250               22
11    Washington Capitals        263            244               19
12   Vegas Golden Knights        265            250               15
13        Edmonton Oilers        282            269               13
10    Philadelphia Flyers        250            243                7
16  Columbus Blue Jackets        253            253                0
18     New York Islanders        233            241               -8
29       New York Rangers        238            250              -12
17          Anaheim Ducks        273            288              -15
15      Detroit Red Wings        241            258              -17
19      Los Angeles Kings        225            247              -22
22    Nashville Predators        247            269              -22
20      New Jersey Devils        230            254              -24
24       Florida Panthers        251            276              -25
21        St. Louis Blues        231            258              -27
25          Winnipeg Jets        231            260              -29
26         Seattle Kraken        226            263              -37
23        San Jose Sharks        251            292              -41
27    Toronto Maple Leafs        253            299              -46
28         Calgary Flames        212            259              -47
30     Chicago Blackhawks        213            275              -62
31      Vancouver Canucks        216            316             -100

In [165]:
# Select the top 5 teams with the highest goal difference
top_5_goal_difference = df.sort_values(by='goal_difference', ascending=False).head(5)

top_5_goal_difference[['team', 'goal_difference']]

                  team  goal_difference
0   Colorado Avalanche               99
4  Tampa Bay Lightning               59
1  Carolina Hurricanes               56
2         Dallas Stars               53
3       Buffalo Sabres               47

In [166]:
# Sort teams by goal difference from lowest to highest
bottom_5_goal_difference = df.sort_values(by='goal_difference', ascending=True).head(5)

bottom_5_goal_difference[['team', 'goal_difference']]

                   team  goal_difference
31    Vancouver Canucks             -100
30   Chicago Blackhawks              -62
28       Calgary Flames              -47
27  Toronto Maple Leafs              -46
23      San Jose Sharks              -41

In [167]:
# Find the team with the lowest goal difference
worst_goal_difference_team = df.loc[df['goal_difference'].idxmin()]

worst_goal_difference_team

team                      Vancouver Canucks
wins                                     25
losses                                   49
ot_losses                                 8
points                                   58
goals_for                               216
goals_against                           316
games_played                             82
goal_difference                        -100
win_percentage                    30.487805
points_per_game                    0.707317
goals_against_per_game             3.853659
goals_for_per_game                 2.634146
Name: 31, dtype: object

In [168]:
# Find the minimum goal difference in the dataset
df['goal_difference'].min()

np.int64(-100)

In [169]:
# Select the top 10 teams based on their total points
top_10_points = df.sort_values(by='points', ascending=False).head(10)

top_10_points[['team', 'points']]

                  team  points
0   Colorado Avalanche     121
1  Carolina Hurricanes     113
2         Dallas Stars     112
3       Buffalo Sabres     109
4  Tampa Bay Lightning     106
5   Montréal Canadiens     106
6       Minnesota Wild     104
7        Boston Bruins     100
8      Ottawa Senators      99
9  Pittsburgh Penguins      98

In [170]:
# Select the top 10 teams based on their number of wins
top_10_wins = df.sort_values(by='wins', ascending=False).head(10)

top_10_wins[['team', 'wins']]

                   team  wins
0    Colorado Avalanche    55
1   Carolina Hurricanes    53
2          Dallas Stars    50
3        Buffalo Sabres    50
4   Tampa Bay Lightning    50
5    Montréal Canadiens    48
6        Minnesota Wild    46
7         Boston Bruins    45
8       Ottawa Senators    44
14         Utah Mammoth    43

In [171]:
# Select the top 10 teams based on goals scored
top_10_goals = df.sort_values(by='goals_for', ascending=False).head(10)

top_10_goals[['team', 'goals_for']]

                   team  goals_for
0    Colorado Avalanche        302
1   Carolina Hurricanes        296
9   Pittsburgh Penguins        293
4   Tampa Bay Lightning        290
3        Buffalo Sabres        288
5    Montréal Canadiens        283
13      Edmonton Oilers        282
2          Dallas Stars        279
8       Ottawa Senators        278
17        Anaheim Ducks        273

In [172]:
# Select the top 10 teams that conceded the fewest goals
top_10_defense = df.sort_values(by='goals_against', ascending=True).head(10)

top_10_defense[['team', 'goals_against']]

                   team  goals_against
0    Colorado Avalanche            203
2          Dallas Stars            226
4   Tampa Bay Lightning            231
1   Carolina Hurricanes            240
14         Utah Mammoth            240
6        Minnesota Wild            240
18   New York Islanders            241
3        Buffalo Sabres            241
10  Philadelphia Flyers            243
11  Washington Capitals            244

In [173]:
# Select the top 10 teams based on their win percentage
top_10_win_percentage = df.sort_values(by='win_percentage', ascending=False).head(10)

top_10_win_percentage[['team', 'win_percentage']]

                   team  win_percentage
0    Colorado Avalanche       67.073171
1   Carolina Hurricanes       64.634146
2          Dallas Stars       60.975610
3        Buffalo Sabres       60.975610
4   Tampa Bay Lightning       60.975610
5    Montréal Canadiens       58.536585
6        Minnesota Wild       56.097561
7         Boston Bruins       54.878049
8       Ottawa Senators       53.658537
14         Utah Mammoth       52.439024

In [174]:
# Select the top 10 teams based on their points per game
top_10_points_per_game = df.sort_values(by='points_per_game', ascending=False).head(10)

top_10_points_per_game[['team', 'points_per_game']]

                  team  points_per_game
0   Colorado Avalanche         1.475610
1  Carolina Hurricanes         1.378049
2         Dallas Stars         1.365854
3       Buffalo Sabres         1.329268
4  Tampa Bay Lightning         1.292683
5   Montréal Canadiens         1.292683
6       Minnesota Wild         1.268293
7        Boston Bruins         1.219512
8      Ottawa Senators         1.207317
9  Pittsburgh Penguins         1.195122

In [175]:
# Select the top 10 teams based on goals scored per game
top_10_goals_per_game = df.sort_values(by='goals_for_per_game', ascending=False).head(10)

top_10_goals_per_game[['team', 'goals_for_per_game']]

                   team  goals_for_per_game
0    Colorado Avalanche            3.682927
1   Carolina Hurricanes            3.609756
9   Pittsburgh Penguins            3.573171
4   Tampa Bay Lightning            3.536585
3        Buffalo Sabres            3.512195
5    Montréal Canadiens            3.451220
13      Edmonton Oilers            3.439024
2          Dallas Stars            3.402439
8       Ottawa Senators            3.390244
17        Anaheim Ducks            3.329268

In [176]:
# Select the top 10 teams based on the fewest goals conceded per game
top_10_goals_against_per_game = df.sort_values(by='goals_against_per_game', ascending=True).head(10)

top_10_goals_against_per_game[['team', 'goals_against_per_game']]

                   team  goals_against_per_game
0    Colorado Avalanche                2.475610
2          Dallas Stars                2.756098
4   Tampa Bay Lightning                2.817073
1   Carolina Hurricanes                2.926829
14         Utah Mammoth                2.926829
6        Minnesota Wild                2.926829
18   New York Islanders                2.939024
3        Buffalo Sabres                2.939024
10  Philadelphia Flyers                2.963415
11  Washington Capitals                2.975610

In [177]:
# Select the top 10 teams based on their goal difference
top_10_goal_difference = df.sort_values(by='goal_difference', ascending=False).head(10)

top_10_goal_difference[['team', 'goal_difference']]

                   team  goal_difference
0    Colorado Avalanche               99
4   Tampa Bay Lightning               59
1   Carolina Hurricanes               56
2          Dallas Stars               53
3        Buffalo Sabres               47
6        Minnesota Wild               32
8       Ottawa Senators               32
14         Utah Mammoth               28
5    Montréal Canadiens               27
9   Pittsburgh Penguins               25

In [178]:
# Compare goals scored and goals conceded for each team
goals_comparison = df[['team', 'goals_for', 'goals_against']].sort_values(
    by='goals_for', ascending=False
)

goals_comparison

                     team  goals_for  goals_against
0      Colorado Avalanche        302            203
1     Carolina Hurricanes        296            240
9     Pittsburgh Penguins        293            268
4     Tampa Bay Lightning        290            231
3          Buffalo Sabres        288            241
5      Montréal Canadiens        283            256
13        Edmonton Oilers        282            269
2            Dallas Stars        279            226
8         Ottawa Senators        278            246
17          Anaheim Ducks        273            288
6          Minnesota Wild        272            240
7           Boston Bruins        272            250
14           Utah Mammoth        268            240
12   Vegas Golden Knights        265            250
11    Washington Capitals        263            244
27    Toronto Maple Leafs        253            299
16  Columbus Blue Jackets        253            253
23        San Jose Sharks        251            292
24       Florida Panthers        251            276
10    Philadelphia Flyers        250            243
22    Nashville Predators        247            269
15      Detroit Red Wings        241            258
29       New York Rangers        238            250
18     New York Islanders        233            241
21        St. Louis Blues        231            258
25          Winnipeg Jets        231            260
20      New Jersey Devils        230            254
26         Seattle Kraken        226            263
19      Los Angeles Kings        225            247
31      Vancouver Canucks        216            316
30     Chicago Blackhawks        213            275
28         Calgary Flames        212            259

In [179]:
# Rank all teams based on their total points
team_ranking = df.sort_values(by='points', ascending=False).reset_index(drop=True)

team_ranking['rank'] = team_ranking.index + 1

team_ranking[['rank', 'team', 'points', 'wins', 'losses', 'ot_losses']]

    rank                   team  points  wins  losses  ot_losses
0      1     Colorado Avalanche     121    55      16         11
1      2    Carolina Hurricanes     113    53      22          7
2      3           Dallas Stars     112    50      20         12
3      4         Buffalo Sabres     109    50      23          9
4      5    Tampa Bay Lightning     106    50      26          6
5      6     Montréal Canadiens     106    48      24         10
6      7         Minnesota Wild     104    46      24         12
7      8          Boston Bruins     100    45      27         10
8      9        Ottawa Senators      99    44      27         11
9     10    Pittsburgh Penguins      98    41      25         16
10    11    Philadelphia Flyers      98    43      27         12
11    12    Washington Capitals      95    43      30          9
12    13   Vegas Golden Knights      95    39      26         17
13    14        Edmonton Oilers      93    41      30         11
14    15          Anaheim Ducks      92    43      33          6
15    16  Columbus Blue Jackets      92    40      30         12
16    17      Detroit Red Wings      92    41      31         10
17    18           Utah Mammoth      92    43      33          6
18    19     New York Islanders      91    43      34          5
19    20      Los Angeles Kings      90    35      27         20
20    21      New Jersey Devils      87    42      37          3
21    22        St. Louis Blues      86    37      33         12
22    23    Nashville Predators      86    38      34         10
23    24        San Jose Sharks      86    39      35          8
24    25       Florida Panthers      84    40      38          4
25    26          Winnipeg Jets      82    35      35         12
26    27         Seattle Kraken      79    34      37         11
27    28    Toronto Maple Leafs      78    32      36         14
28    29         Calgary Flames      77    34      39          9
29    30       New York Rangers      77    34      39          9
30    31     Chicago Blackhawks      72    29      39         14
31    32      Vancouver Canucks      58    25      49          8

In [180]:
# Select the bottom 10 teams based on their total points
bottom_10_points = df.sort_values(by='points', ascending=True).head(10)

bottom_10_points[['team', 'points']]

                   team  points
31    Vancouver Canucks      58
30   Chicago Blackhawks      72
29     New York Rangers      77
28       Calgary Flames      77
27  Toronto Maple Leafs      78
26       Seattle Kraken      79
25        Winnipeg Jets      82
24     Florida Panthers      84
23      San Jose Sharks      86
22  Nashville Predators      86

In [181]:
# Count the total number of teams in the dataset
total_teams = df['team'].nunique()

total_teams

32

In [182]:
# Check for duplicate team names in the dataset
duplicate_teams = df['team'].duplicated().sum()

duplicate_teams

np.int64(0)

In [183]:
# Display the top-level keys available in the NHL API response
print(data.keys())

dict_keys(['wildCardIndicator', 'standingsDateTimeUtc', 'standings'])

In [184]:
import requests

# NHL standings API URL
url = "https://api-web.nhle.com/v1/standings/now"

response = requests.get(url)

# Convert the JSON response into a Python dictionary
data = response.json()

print(data)

{'wildCardIndicator': True, 'standingsDateTimeUtc': '2026-09-15T10:57:15Z', 'standings': [{'clinchIndicator': 'p', 'conferenceAbbrev': 'W', 'conferenceHomeSequence': 1, 'conferenceL10Sequence': 2, 'conferenceName': 'Western', 'conferenceRoadSequence': 1, 'conferenceSequence': 1, 'date': '2026-04-17', 'divisionAbbrev': 'C', 'divisionHomeSequence': 1, 'divisionL10Sequence': 1, 'divisionName': 'Central', 'divisionRoadSequence': 1, 'divisionSequence': 1, 'gameTypeId': 2, 'gamesPlayed': 82, 'goalDifferential': 99, 'goalDifferentialPctg': 1.207317, 'goalAgainst': 203, 'goalFor': 302, 'goalsForPctg': 3.682927, 'homeGamesPlayed': 41, 'homeGoalDifferential': 49, 'homeGoalsAgainst': 108, 'homeGoalsFor': 157, 'homeLosses': 9, 'homeOtLosses': 6, 'homePoints': 58, 'homeRegulationPlusOtWins': 25, 'homeRegulationWins': 25, 'homeTies': 0, 'homeWins': 26, 'l10GamesPlayed': 10, 'l10GoalDifferential': 14, 'l10GoalsAgainst': 20, 'l10GoalsFor': 34, 'l10Losses': 2, 'l10OtLosses': 1, 'l10Points': 15, 'l10RegulationPlusOtWins': 6, 'l10RegulationWins': 6, 'l10Ties': 0, 'l10Wins': 7, 'leagueHomeSequence': 3, 'leagueL10Sequence': 4, 'leagueRoadSequence': 1, 'leagueSequence': 1, 'losses': 16, 'otLosses': 11, 'placeName': {'default': 'Colorado'}, 'pointPctg': 0.737805, 'points': 121, 'regulationPlusOtWinPctg': 0.621951, 'regulationPlusOtWins': 51, 'regulationWinPctg': 0.585366, 'regulationWins': 48, 'roadGamesPlayed': 41, 'roadGoalDifferential': 50, 'roadGoalsAgainst': 95, 'roadGoalsFor': 145, 'roadLosses': 7, 'roadOtLosses': 5, 'roadPoints': 63, 'roadRegulationPlusOtWins': 26, 'roadRegulationWins': 23, 'roadTies': 0, 'roadWins': 29, 'seasonId': 20252026, 'shootoutLosses': 6, 'shootoutWins': 4, 'streakCode': 'W', 'streakCount': 3, 'teamName': {'default': 'Colorado Avalanche', 'fr': 'Avalanche du Colorado'}, 'teamCommonName': {'default': 'Avalanche'}, 'teamAbbrev': {'default': 'COL'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg', 'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/COL_dark.svg', 'ties': 0, 'waiversSequence': 32, 'wildcardSequence': 0, 'winPctg': 0.670732, 'wins': 55}, {'clinchIndicator': 'z', 'conferenceAbbrev': 'E', 'conferenceHomeSequence': 1, 'conferenceL10Sequence': 2, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 3, 'conferenceSequence': 1, 'date': '2026-04-17', 'divisionAbbrev': 'M', 'divisionHomeSequence': 1, 'divisionL10Sequence': 2, 'divisionName': 'Metropolitan', 'divisionRoadSequence': 1, 'divisionSequence': 1, 'gameTypeId': 2, 'gamesPlayed': 82, 'goalDifferential': 56, 'goalDifferentialPctg': 0.682927, 'goalAgainst': 240, 'goalFor': 296, 'goalsForPctg': 3.609756, 'homeGamesPlayed': 41, 'homeGoalDifferential': 35, 'homeGoalsAgainst': 126, 'homeGoalsFor': 161, 'homeLosses': 10, 'homeOtLosses': 2, 'homePoints': 60, 'homeRegulationPlusOtWins': 27, 'homeRegulationWins': 20, 'homeTies': 0, 'homeWins': 29, 'l10GamesPlayed': 10, 'l10GoalDifferential': 12, 'l10GoalsAgainst': 27, 'l10GoalsFor': 39, 'l10Losses': 2, 'l10OtLosses': 1, 'l10Points': 15, 'l10RegulationPlusOtWins': 7, 'l10RegulationWins': 6, 'l10Ties': 0, 'l10Wins': 7, 'leagueHomeSequence': 1, 'leagueL10Sequence': 3, 'leagueRoadSequence': 5, 'leagueSequence': 2, 'losses': 22, 'otLosses': 7, 'placeName': {'default': 'Carolina', 'fr': 'Caroline'}, 'pointPctg': 0.689024, 'points': 113, 'regulationPlusOtWinPctg': 0.585366, 'regulationPlusOtWins': 48, 'regulationWinPctg': 0.47561, 'regulationWins': 39, 'roadGamesPlayed': 41, 'roadGoalDifferential': 21, 'roadGoalsAgainst': 114, 'roadGoalsFor': 135, 'roadLosses': 12, 'roadOtLosses': 5, 'roadPoints': 53, 'roadRegulationPlusOtWins': 21, 'roadRegulationWins': 19, 'roadTies': 0, 'roadWins': 24, 'seasonId': 20252026, 'shootoutLosses': 4, 'shootoutWins': 5, 'streakCode': 'W', 'streakCount': 1, 'teamName': {'default': 'Carolina Hurricanes', 'fr': 'Hurricanes de la Caroline'}, 'teamCommonName': {'default': 'Hurricanes'}, 'teamAbbrev': {'default': 'CAR'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/CAR_light.svg', 'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/CAR_dark.svg', 'ties': 0, 'waiversSequence': 31, 'wildcardSequence': 0, 'winPctg': 0.646341, 'wins': 53}, {'clinchIndicator': 'x', 'conferenceAbbrev': 'W', 'conferenceHomeSequence': 2, 'conferenceL10Sequence': 3, 'conferenceName': 'Western', 'conferenceRoadSequence': 2, 'conferenceSequence': 2, 'date': '2026-04-17', 'divisionAbbrev': 'C', 'divisionHomeSequence': 2, 'divisionL10Sequence': 2, 'divisionName': 'Central', 'divisionRoadSequence': 2, 'divisionSequence': 2, 'gameTypeId': 2, 'gamesPlayed': 82, 'goalDifferential': 53, 'goalDifferentialPctg': 0.646341, 'goalAgainst': 226, 'goalFor': 279, 'goalsForPctg': 3.402439, 'homeGamesPlayed': 41, 'homeGoalDifferential': 23, 'homeGoalsAgainst': 112, 'homeGoalsFor': 135, 'homeLosses': 11, 'homeOtLosses': 4, 'homePoints': 56, 'homeRegulationPlusOtWins': 24, 'homeRegulationWins': 19, 'homeTies': 0, 'homeWins': 26, 'l10GamesPlayed': 10, 'l10GoalDifferential': 6, 'l10GoalsAgainst': 28, 'l10GoalsFor': 34, 'l10Losses': 2, 'l10OtLosses': 1, 'l10Points': 15, 'l10RegulationPlusOtWins': 6, 'l10RegulationWins': 5, 'l10Ties': 0, 'l10Wins': 7, 'leagueHomeSequence': 5, 'leagueL10Sequence': 5, 'leagueRoadSequence': 2, 'leagueSequence': 3, 'losses': 20, 'otLosses': 12, 'placeName': {'default': 'Dallas'}, 'pointPctg': 0.682927, 'points': 112, 'regulationPlusOtWinPctg': 0.536585, 'regulationPlusOtWins': 44, 'regulationWinPctg': 0.463415, 'regulationWins': 38, 'roadGamesPlayed': 41, 'roadGoalDifferential': 30, 'roadGoalsAgainst': 114, 'roadGoalsFor': 144, 'roadLosses': 9, 'roadOtLosses': 8, 'roadPoints': 56, 'roadRegulationPlusOtWins': 20, 'roadRegulationWins': 19, 'roadTies': 0, 'roadWins': 24, 'seasonId': 20252026, 'shootoutLosses': 4, 'shootoutWins': 6, 'streakCode': 'W', 'streakCount': 5, 'teamName': {'default': 'Dallas Stars', 'fr': 'Stars de Dallas'}, 'teamCommonName': {'default': 'Stars'}, 'teamAbbrev': {'default': 'DAL'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/DAL_light.svg', 'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/DAL_dark.svg', 'ties': 0, 'waiversSequence': 30, 'wildcardSequence': 0, 'winPctg': 0.609756, 'wins': 50}, {'clinchIndicator': 'y', 'conferenceAbbrev': 'E', 'conferenceHomeSequence': 3, 'conferenceL10Sequence': 6, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 4, 'conferenceSequence': 2, 'date': '2026-04-17', 'divisionAbbrev': 'A', 'divisionHomeSequence': 2, 'divisionL10Sequence': 3, 'divisionName': 'Atlantic', 'divisionRoadSequence': 3, 'divisionSequence': 1, 'gameTypeId': 2, 'gamesPlayed': 82, 'goalDifferential': 47, 'goalDifferentialPctg': 0.573171, 'goalAgainst': 241, 'goalFor': 288, 'goalsForPctg': 3.512195, 'homeGamesPlayed': 41, 'homeGoalDifferential': 30, 'homeGoalsAgainst': 119, 'homeGoalsFor': 149, 'homeLosses': 10, 'homeOtLosses': 5, 'homePoints': 57, 'homeRegulationPlusOtWins': 22, 'homeRegulationWins': 22, 'homeTies': 0, 'homeWins': 26, 'l10GamesPlayed': 10, 'l10GoalDifferential': 4, 'l10GoalsAgainst': 30, 'l10GoalsFor': 34, 'l10Losses': 3, 'l10OtLosses': 1, 'l10Points': 13, 'l10RegulationPlusOtWins': 5, 'l10RegulationWins': 5, 'l10Ties': 0, 'l10Wins': 6, 'leagueHomeSequence': 4, 'leagueL10Sequence': 12, 'leagueRoadSequence': 6, 'leagueSequence': 4, 'losses': 23, 'otLosses': 9, 'placeName': {'default': 'Buffalo'}, 'pointPctg': 0.664634, 'points': 109, 'regulationPlusOtWinPctg': 0.54878, 'regulationPlusOtWins': 45, 'regulationWinPctg': 0.512195, 'regulationWins': 42, 'roadGamesPlayed': 41, 'roadGoalDifferential': 17, 'roadGoalsAgainst': 122, 'roadGoalsFor': 139, 'roadLosses': 13, 'roadOtLosses': 4, 'roadPoints': 52, 'roadRegulationPlusOtWins': 23, 'roadRegulationWins': 20, 'roadTies': 0, 'roadWins': 24, 'seasonId': 20252026, 'shootoutLosses': 1, 'shootoutWins': 5, 'streakCode': 'OT', 'streakCount': 1, 'teamName': {'default': 'Buffalo Sabres', 'fr': 'Sabres de Buffalo'}, 'teamCommonName': {'default': 'Sabres'}, 'teamAbbrev': {'default': 'BUF'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/BUF_light.svg', 'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/BUF_dark.svg', 'ties': 0, 'waiversSequence': 29, 'wildcardSequence': 0, 'winPctg': 0.609756, 'wins': 50}, {'clinchIndicator': 'x', 'conferenceAbbrev': 'E', 'conferenceHomeSequence': 5, 'conferenceL10Sequence': 12, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 2, 'conferenceSequence': 3, 'date': '2026-04-17', 'divisionAbbrev': 'A', 'divisionHomeSequence': 3, 'divisionL10Sequence': 6, 'divisionName': 'Atlantic', 'divisionRoadSequence': 2, 'divisionSequence': 2, 'gameTypeId': 2, 'gamesPlayed': 82, 'goalDifferential': 59, 'goalDifferentialPctg': 0.719512, 'goalAgainst': 231, 'goalFor': 290, 'goalsForPctg': 3.536585, 'homeGamesPlayed': 41, 'homeGoalDifferential': 22, 'homeGoalsAgainst': 115, 'homeGoalsFor': 137, 'homeLosses': 14, 'homeOtLosses': 1, 'homePoints': 53, 'homeRegulationPlusOtWins': 24, 'homeRegulationWins': 19, 'homeTies': 0, 'homeWins': 26, 'l10GamesPlayed': 10, 'l10GoalDifferential': -4, 'l10GoalsAgainst': 30, 'l10GoalsFor': 26, 'l10Losses': 5, 'l10OtLosses': 0, 'l10Points': 10, 'l10RegulationPlusOtWins': 5, 'l10RegulationWins': 4, 'l10Ties': 0, 'l10Wins': 5, 'leagueHomeSequence': 8, 'leagueL10Sequence': 21, 'leagueRoadSequence': 4, 'leagueSequence': 5, 'losses': 26, 'otLosses': 6, 'placeName': {'default': 'Tampa Bay'}, 'pointPctg': 0.646341, 'points': 106, 'regulationPlusOtWinPctg': 0.560976, 'regulationPlusOtWins': 46, 'regulationWinPctg': 0.487805, 'regulationWins': 40, 'roadGamesPlayed': 41, 'roadGoalDifferential': 37, 'roadGoalsAgainst': 116, 'roadGoalsFor': 153, 'roadLosses': 12, 'roadOtLosses': 5, 'roadPoints': 53, 'roadRegulationPlusOtWins': 22, 'roadRegulationWins': 21, 'roadTies': 0, 'roadWins': 24, 'seasonId': 20252026, 'shootoutLosses': 2, 'shootoutWins': 4, 'streakCode': 'L', 'streakCount': 1, 'teamName': {'default': 'Tampa Bay Lightning', 'fr': 'Lightning de Tampa Bay'}, 'teamCommonName': {'default': 'Lightning'}, 'teamAbbrev': {'default': 'TBL'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/TBL_light.svg', 'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/TBL_dark.svg', 'ties': 0, 'waiversSequence': 28, 'wildcardSequence': 0, 'winPctg': 0.609756, 'wins': 50}, {'clinchIndicator': 'x', 'conferenceAbbrev': 'E', 'conferenceHomeSequence': 7, 'conferenceL10Sequence': 3, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 1, 'conferenceSequence': 4, 'date': '2026-04-17', 'divisionAbbrev': 'A', 'divisionHomeSequence': 5, 'divisionL10Sequence': 1, 'divisionName': 'Atlantic', 'divisionRoadSequence': 1, 'divisionSequence': 3, 'gameTypeId': 2, 'gamesPlayed': 82, 'goalDifferential': 27, 'goalDifferentialPctg': 0.329268, 'goalAgainst': 256, 'goalFor': 283, 'goalsForPctg': 3.45122, 'homeGamesPlayed': 41, 'homeGoalDifferential': 10, 'homeGoalsAgainst': 127, 'homeGoalsFor': 137, 'homeLosses': 15, 'homeOtLosses': 2, 'homePoints': 50, 'homeRegulationPlusOtWins': 22, 'homeRegulationWins': 17, 'homeTies': 0, 'homeWins': 24, 'l10GamesPlayed': 10, 'l10GoalDifferential': 4, 'l10GoalsAgainst': 24, 'l10GoalsFor': 28, 'l10Losses': 3, 'l10OtLosses': 0, 'l10Points': 14, 'l10RegulationPlusOtWins': 5, 'l10RegulationWins': 5, 'l10Ties': 0, 'l10Wins': 7, 'leagueHomeSequence': 12, 'leagueL10Sequence': 7, 'leagueRoadSequence': 3, 'leagueSequence': 6, 'losses': 24, 'otLosses': 10, 'placeName': {'default': 'Montréal'}, 'pointPctg': 0.646341, 'points': 106, 'regulationPlusOtWinPctg': 0.536585, 'regulationPlusOtWins': 44, 'regulationWinPctg': 0.414634, 'regulationWins': 34, 'roadGamesPlayed': 41, 'roadGoalDifferential': 17, 'roadGoalsAgainst': 129, 'roadGoalsFor': 146, 'roadLosses': 9, 'roadOtLosses': 8, 'roadPoints': 56, 'roadRegulationPlusOtWins': 22, 'roadRegulationWins': 17, 'roadTies': 0, 'roadWins': 24, 'seasonId': 20252026, 'shootoutLosses': 5, 'shootoutWins': 4, 'streakCode': 'L', 'streakCount': 1, 'teamName': {'default': 'Montréal Canadiens', 'fr': 'Canadiens de Montréal'}, 'teamCommonName': {'default': 'Canadiens'}, 'teamAbbrev': {'default': 'MTL'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MTL_light.svg', 'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/MTL_dark.svg', 'ties': 0, 'waiversSequence': 27, 'wildcardSequence': 0, 'winPctg': 0.585366, 'wins': 48}, {'clinchIndicator': 'x', 'conferenceAbbrev': 'W', 'conferenceHomeSequence': 3, 'conferenceL10Sequence': 7, 'conferenceName': 'Western', 'conferenceRoadSequence': 4, 'conferenceSequence': 3, 'date': '2026-04-17', 'divisionAbbrev': 'C', 'divisionHomeSequence': 3, 'divisionL10Sequence': 4, 'divisionName': 'Central', 'divisionRoadSequence': 3, 'divisionSequence': 3, 'gameTypeId': 2, 'gamesPlayed': 82, 'goalDifferential': 32, 'goalDifferentialPctg': 0.390244, 'goalAgainst': 240, 'goalFor': 272, 'goalsForPctg': 3.317073, 'homeGamesPlayed': 41, 'homeGoalDifferential': 15, 'homeGoalsAgainst': 115, 'homeGoalsFor': 130, 'homeLosses': 10, 'homeOtLosses': 8, 'homePoints': 54, 'homeRegulationPlusOtWins': 19, 'homeRegulationWins': 14, 'homeTies': 0, 'homeWins': 23, 'l10GamesPlayed': 10, 'l10GoalDifferential': 4, 'l10GoalsAgainst': 32, 'l10GoalsFor': 36, 'l10Losses': 4, 'l10OtLosses': 0, 'l10Points': 12, 'l10RegulationPlusOtWins': 6, 'l10RegulationWins': 6, 'l10Ties': 0, 'l10Wins': 6, 'leagueHomeSequence': 7, 'leagueL10Sequence': 14, 'leagueRoadSequence': 9, 'leagueSequence': 7, 'losses': 24, 'otLosses': 12, 'placeName': {'default': 'Minnesota'}, 'pointPctg': 0.634146, 'points': 104, 'regulationPlusOtWinPctg': 0.512195, 'regulationPlusOtWins': 42, 'regulationWinPctg': 0.378049, 'regulationWins': 31, 'roadGamesPlayed': 41, 'roadGoalDifferential': 17, 'roadGoalsAgainst': 125, 'roadGoalsFor': 142, 'roadLosses': 14, 'roadOtLosses': 4, 'roadPoints': 50, 'roadRegulationPlusOtWins': 23, 'roadRegulationWins': 17, 'roadTies': 0, 'roadWins': 23, 'seasonId': 20252026, 'shootoutLosses': 5, 'shootoutWins': 4, 'streakCode': 'W', 'streakCount': 1, 'teamName': {'default': 'Minnesota Wild', 'fr': 'Wild du Minnesota'}, 'teamCommonName': {'default': 'Wild'}, 'teamAbbrev': {'default': 'MIN'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MIN_light.svg', 'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/MIN_dark.svg', 'ties': 0, 'waiversSequence': 26, 'wildcardSequence': 0, 'winPctg': 0.560976, 'wins': 46}, {'clinchIndicator': 'x', 'conferenceAbbrev': 'E', 'conferenceHomeSequence': 2, 'conferenceL10Sequence': 8, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 13, 'conferenceSequence': 5, 'date': '2026-04-17', 'divisionAbbrev': 'A', 'divisionHomeSequence': 1, 'divisionL10Sequence': 4, 'divisionName': 'Atlantic', 'divisionRoadSequence': 6, 'divisionSequence': 4, 'gameTypeId': 2, 'gamesPlayed': 82, 'goalDifferential': 22, 'goalDifferentialPctg': 0.268293, 'goalAgainst': 250, 'goalFor': 272, 'goalsForPctg': 3.317073, 'homeGamesPlayed': 41, 'homeGoalDifferential': 40, 'homeGoalsAgainst': 105, 'homeGoalsFor': 145, 'homeLosses': 11, 'homeOtLosses': 1, 'homePoints': 59, 'homeRegulationPlusOtWins': 28, 'homeRegulationWins': 23, 'homeTies': 0, 'homeWins': 29, 'l10GamesPlayed': 10, 'l10GoalDifferential': 6, 'l10GoalsAgainst': 26, 'l10GoalsFor': 32, 'l10Losses': 3, 'l10OtLosses': 2, 'l10Points': 12, 'l10RegulationPlusOtWins': 4, 'l10RegulationWins': 4, 'l10Ties': 0, 'l10Wins': 5, 'leagueHomeSequence': 2, 'leagueL10Sequence': 16, 'leagueRoadSequence': 21, 'leagueSequence': 8, 'losses': 27, 'otLosses': 10, 'placeName': {'default': 'Boston'}, 'pointPctg': 0.609756, 'points': 100, 'regulationPlusOtWinPctg': 0.5, 'regulationPlusOtWins': 41, 'regulationWinPctg': 0.402439, 'regulationWins': 33, 'roadGamesPlayed': 41, 'roadGoalDifferential': -18, 'roadGoalsAgainst': 145, 'roadGoalsFor': 127, 'roadLosses': 16, 'roadOtLosses': 9, 'roadPoints': 41, 'roadRegulationPlusOtWins': 13, 'roadRegulationWins': 10, 'roadTies': 0, 'roadWins': 16, 'seasonId': 20252026, 'shootoutLosses': 3, 'shootoutWins': 4, 'streakCode': 'W', 'streakCount': 2, 'teamName': {'default': 'Boston Bruins', 'fr': 'Bruins de Boston'}, 'teamCommonName': {'default': 'Bruins'}, 'teamAbbrev': {'default': 'BOS'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/BOS_light.svg?season=20252026', 'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/BOS_dark.svg?season=20252026', 'ties': 0, 'waiversSequence': 25, 'wildcardSequence': 1, 'winPctg': 0.54878, 'wins': 45}, {'clinchIndicator': 'x', 'conferenceAbbrev': 'E', 'conferenceHomeSequence': 6, 'conferenceL10Sequence': 5, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 7, 'conferenceSequence': 6, 'date': '2026-04-17', 'divisionAbbrev': 'A', 'divisionHomeSequence': 4, 'divisionL10Sequence': 2, 'divisionName': 'Atlantic', 'divisionRoadSequence': 4, 'divisionSequence': 5, 'gameTypeId': 2, 'gamesPlayed': 82, 'goalDifferential': 32, 'goalDifferentialPctg': 0.390244, 'goalAgainst': 246, 'goalFor': 278, 'goalsForPctg': 3.390244, 'homeGamesPlayed': 41, 'homeGoalDifferential': 31, 'homeGoalsAgainst': 108, 'homeGoalsFor': 139, 'homeLosses': 12, 'homeOtLosses': 6, 'homePoints': 52, 'homeRegulationPlusOtWins': 21, 'homeRegulationWins': 21, 'homeTies': 0, 'homeWins': 23, 'l10GamesPlayed': 10, 'l10GoalDifferential': 10, 'l10GoalsAgainst': 26, 'l10GoalsFor': 36, 'l10Losses': 3, 'l10OtLosses': 1, 'l10Points': 13, 'l10RegulationPlusOtWins': 6, 'l10RegulationWins': 6, 'l10Ties': 0, 'l10Wins': 6, 'leagueHomeSequence': 9, 'leagueL10Sequence': 10, 'leagueRoadSequence': 11, 'leagueSequence': 9, 'losses': 27, 'otLosses': 11, 'placeName': {'default': 'Ottawa'}, 'pointPctg': 0.603659, 'points': 99, 'regulationPlusOtWinPctg': 0.5, 'regulationPlusOtWins': 41, 'regulationWinPctg': 0.463415, 'regulationWins': 38, 'roadGamesPlayed': 41, 'roadGoalDifferential': 1, 'roadGoalsAgainst': 138, 'roadGoalsFor': 139, 'roadLosses': 15, 'roadOtLosses': 5, 'roadPoints': 47, 'roadRegulationPlusOtWins': 20, 'roadRegulationWins': 17, 'roadTies': 0, 'roadWins': 21, 'seasonId': 20252026, 'shootoutLosses': 1, 'shootoutWins': 3, 'streakCode': 'W', 'streakCount': 1, 'teamName': {'default': 'Ottawa Senators', 'fr': "Sénateurs d'Ottawa"}, 'teamCommonName': {'default': 'Senators', 'fr': 'Sénateurs'}, 'teamAbbrev': {'default': 'OTT'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/OTT_light.svg', 'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/OTT_dark.svg', 'ties': 0, 'waiversSequence': 24, 'wildcardSequence': 2, 'winPctg': 0.536585, 'wins': 44}, {'clinchIndicator': 'x', 'conferenceAbbrev': 'E', 'conferenceHomeSequence': 10, 'conferenceL10Sequence': 11, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 5, 'conferenceSequence': 7, 'date': '2026-04-17', 'divisionAbbrev': 'M', 'divisionHomeSequence': 4, 'divisionL10Sequence': 6, 'divisionName': 'Metropolitan', 'divisionRoadSequence': 2, 'divisionSequence': 2, 'gameTypeId': 2, 'gamesPlayed': 82, 'goalDifferential': 25, 'goalDifferentialPctg': 0.304878, 'goalAgainst': 268, 'goalFor': 293, 'goalsForPctg': 3.573171, 'homeGamesPlayed': 41, 'homeGoalDifferential': 7, 'homeGoalsAgainst': 143, 'homeGoalsFor': 150, 'homeLosses': 13, 'homeOtLosses': 8, 'homePoints': 48, 'homeRegulationPlusOtWins': 18, 'homeRegulationWins': 16, 'homeTies': 0, 'homeWins': 20, 'l10GamesPlayed': 10, 'l10GoalDifferential': 6, 'l10GoalsAgainst': 40, 'l10GoalsFor': 46, 'l10Losses': 5, 'l10OtLosses': 0, 'l10Points': 10, 'l10RegulationPlusOtWins': 5, 'l10RegulationWins': 5, 'l10Ties': 0, 'l10Wins': 5, 'leagueHomeSequence': 17, 'leagueL10Sequence': 20, 'leagueRoadSequence': 8, 'leagueSequence': 10, 'losses': 25, 'otLosses': 16, 'placeName': {'default': 'Pittsburgh'}, 'pointPctg': 0.597561, 'points': 98, 'regulationPlusOtWinPctg': 0.463415, 'regulationPlusOtWins': 38, 'regulationWinPctg': 0.414634, 'regulationWins': 34, 'roadGamesPlayed': 41, 'roadGoalDifferential': 18, 'roadGoalsAgainst': 125, 'roadGoalsFor': 143, 'roadLosses': 12, 'roadOtLosses': 8, 'roadPoints': 50, 'roadRegulationPlusOtWins': 20, 'roadRegulationWins': 18, 'roadTies': 0, 'roadWins': 21, 'seasonId': 20252026, 'shootoutLosses': 10, 'shootoutWins': 3, 'streakCode': 'L', 'streak

In [185]:
# Display the top-level keys available in the NHL API response
print(data.keys())

dict_keys(['wildCardIndicator', 'standingsDateTimeUtc', 'standings'])

In [186]:
# Extract the team standings from the API response
standings = data["standings"]

print(type(standings))

<class 'list'>

In [187]:
# Count the number of team records in the standings
print(len(standings))

32

In [188]:
# Display the complete record of the first team
print(standings[0])

{'clinchIndicator': 'p', 'conferenceAbbrev': 'W', 'conferenceHomeSequence': 1, 'conferenceL10Sequence': 2, 'conferenceName': 'Western', 'conferenceRoadSequence': 1, 'conferenceSequence': 1, 'date': '2026-04-17', 'divisionAbbrev': 'C', 'divisionHomeSequence': 1, 'divisionL10Sequence': 1, 'divisionName': 'Central', 'divisionRoadSequence': 1, 'divisionSequence': 1, 'gameTypeId': 2, 'gamesPlayed': 82, 'goalDifferential': 99, 'goalDifferentialPctg': 1.207317, 'goalAgainst': 203, 'goalFor': 302, 'goalsForPctg': 3.682927, 'homeGamesPlayed': 41, 'homeGoalDifferential': 49, 'homeGoalsAgainst': 108, 'homeGoalsFor': 157, 'homeLosses': 9, 'homeOtLosses': 6, 'homePoints': 58, 'homeRegulationPlusOtWins': 25, 'homeRegulationWins': 25, 'homeTies': 0, 'homeWins': 26, 'l10GamesPlayed': 10, 'l10GoalDifferential': 14, 'l10GoalsAgainst': 20, 'l10GoalsFor': 34, 'l10Losses': 2, 'l10OtLosses': 1, 'l10Points': 15, 'l10RegulationPlusOtWins': 6, 'l10RegulationWins': 6, 'l10Ties': 0, 'l10Wins': 7, 'leagueHomeSequence': 3, 'leagueL10Sequence': 4, 'leagueRoadSequence': 1, 'leagueSequence': 1, 'losses': 16, 'otLosses': 11, 'placeName': {'default': 'Colorado'}, 'pointPctg': 0.737805, 'points': 121, 'regulationPlusOtWinPctg': 0.621951, 'regulationPlusOtWins': 51, 'regulationWinPctg': 0.585366, 'regulationWins': 48, 'roadGamesPlayed': 41, 'roadGoalDifferential': 50, 'roadGoalsAgainst': 95, 'roadGoalsFor': 145, 'roadLosses': 7, 'roadOtLosses': 5, 'roadPoints': 63, 'roadRegulationPlusOtWins': 26, 'roadRegulationWins': 23, 'roadTies': 0, 'roadWins': 29, 'seasonId': 20252026, 'shootoutLosses': 6, 'shootoutWins': 4, 'streakCode': 'W', 'streakCount': 3, 'teamName': {'default': 'Colorado Avalanche', 'fr': 'Avalanche du Colorado'}, 'teamCommonName': {'default': 'Avalanche'}, 'teamAbbrev': {'default': 'COL'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg', 'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/COL_dark.svg', 'ties': 0, 'waiversSequence': 32, 'wildcardSequence': 0, 'winPctg': 0.670732, 'wins': 55}

In [189]:
# Extract the team name from the first team's record
print(standings[0]["teamName"]["default"])

Colorado Avalanche

In [190]:
# Extract the team's abbreviation
print(standings[0]["teamAbbrev"]["default"])

COL

In [191]:
# Extract the team's wins, losses, and points
print("Wins:", standings[0]["wins"])
print("Losses:", standings[0]["losses"])
print("Points:", standings[0]["points"])

Wins: 55
Losses: 16
Points: 121

In [192]:
# Loop through all team records and display each team's name
for team in standings:
    print(team["teamName"]["default"])

Colorado Avalanche
Carolina Hurricanes
Dallas Stars
Buffalo Sabres
Tampa Bay Lightning
Montréal Canadiens
Minnesota Wild
Boston Bruins
Ottawa Senators
Pittsburgh Penguins
Philadelphia Flyers
Washington Capitals
Vegas Golden Knights
Edmonton Oilers
Utah Mammoth
Detroit Red Wings
Columbus Blue Jackets
Anaheim Ducks
New York Islanders
Los Angeles Kings
New Jersey Devils
St. Louis Blues
Nashville Predators
San Jose Sharks
Florida Panthers
Winnipeg Jets
Seattle Kraken
Toronto Maple Leafs
Calgary Flames
New York Rangers
Chicago Blackhawks
Vancouver Canucks

In [193]:
# Loop through all teams and display their basic standings information
for team in standings:
    print(
        team["teamName"]["default"],
        "| Wins:", team["wins"],
        "| Losses:", team["losses"],
        "| Points:", team["points"]
    )

Colorado Avalanche | Wins: 55 | Losses: 16 | Points: 121
Carolina Hurricanes | Wins: 53 | Losses: 22 | Points: 113
Dallas Stars | Wins: 50 | Losses: 20 | Points: 112
Buffalo Sabres | Wins: 50 | Losses: 23 | Points: 109
Tampa Bay Lightning | Wins: 50 | Losses: 26 | Points: 106
Montréal Canadiens | Wins: 48 | Losses: 24 | Points: 106
Minnesota Wild | Wins: 46 | Losses: 24 | Points: 104
Boston Bruins | Wins: 45 | Losses: 27 | Points: 100
Ottawa Senators | Wins: 44 | Losses: 27 | Points: 99
Pittsburgh Penguins | Wins: 41 | Losses: 25 | Points: 98
Philadelphia Flyers | Wins: 43 | Losses: 27 | Points: 98
Washington Capitals | Wins: 43 | Losses: 30 | Points: 95
Vegas Golden Knights | Wins: 39 | Losses: 26 | Points: 95
Edmonton Oilers | Wins: 41 | Losses: 30 | Points: 93
Utah Mammoth | Wins: 43 | Losses: 33 | Points: 92
Detroit Red Wings | Wins: 41 | Losses: 31 | Points: 92
Columbus Blue Jackets | Wins: 40 | Losses: 30 | Points: 92
Anaheim Ducks | Wins: 43 | Losses: 33 | Points: 92
New York Islanders | Wins: 43 | Losses: 34 | Points: 91
Los Angeles Kings | Wins: 35 | Losses: 27 | Points: 90
New Jersey Devils | Wins: 42 | Losses: 37 | Points: 87
St. Louis Blues | Wins: 37 | Losses: 33 | Points: 86
Nashville Predators | Wins: 38 | Losses: 34 | Points: 86
San Jose Sharks | Wins: 39 | Losses: 35 | Points: 86
Florida Panthers | Wins: 40 | Losses: 38 | Points: 84
Winnipeg Jets | Wins: 35 | Losses: 35 | Points: 82
Seattle Kraken | Wins: 34 | Losses: 37 | Points: 79
Toronto Maple Leafs | Wins: 32 | Losses: 36 | Points: 78
Calgary Flames | Wins: 34 | Losses: 39 | Points: 77
New York Rangers | Wins: 34 | Losses: 39 | Points: 77
Chicago Blackhawks | Wins: 29 | Losses: 39 | Points: 72
Vancouver Canucks | Wins: 25 | Losses: 49 | Points: 58

In [194]:
# Check how many team records are stored in teams_data
print(len(teams_data))

32

In [195]:
# Display the first 5 structured team records
print(teams_data[:5])

[{'team_abbrev': 'COL', 'team_name': 'Colorado Avalanche', 'conference_name': 'Western', 'division_name': 'Central', 'logo_url': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg'}, {'team_abbrev': 'CAR', 'team_name': 'Carolina Hurricanes', 'conference_name': 'Eastern', 'division_name': 'Metropolitan', 'logo_url': 'https://assets.nhle.com/logos/nhl/svg/CAR_light.svg'}, {'team_abbrev': 'DAL', 'team_name': 'Dallas Stars', 'conference_name': 'Western', 'division_name': 'Central', 'logo_url': 'https://assets.nhle.com/logos/nhl/svg/DAL_light.svg'}, {'team_abbrev': 'BUF', 'team_name': 'Buffalo Sabres', 'conference_name': 'Eastern', 'division_name': 'Atlantic', 'logo_url': 'https://assets.nhle.com/logos/nhl/svg/BUF_light.svg'}, {'team_abbrev': 'TBL', 'team_name': 'Tampa Bay Lightning', 'conference_name': 'Eastern', 'division_name': 'Atlantic', 'logo_url': 'https://assets.nhle.com/logos/nhl/svg/TBL_light.svg'}]

In [196]:
import pandas as pd

# Convert the team list into a Pandas DataFrame
df = pd.DataFrame(teams_data)

print(df.head())

  team_abbrev            team_name conference_name division_name  \
0         COL   Colorado Avalanche         Western       Central
1         CAR  Carolina Hurricanes         Eastern  Metropolitan
2         DAL         Dallas Stars         Western       Central
3         BUF       Buffalo Sabres         Eastern      Atlantic
4         TBL  Tampa Bay Lightning         Eastern      Atlantic

                                            logo_url
0  https://assets.nhle.com/logos/nhl/svg/COL_ligh...
1  https://assets.nhle.com/logos/nhl/svg/CAR_ligh...
2  https://assets.nhle.com/logos/nhl/svg/DAL_ligh...
3  https://assets.nhle.com/logos/nhl/svg/BUF_ligh...
4  https://assets.nhle.com/logos/nhl/svg/TBL_ligh...

In [197]:
# Check the number of rows and columns in the DataFrame
print(df.shape)

(32, 5)

In [198]:
teams_data = [] #empty list to store the required team information

# Extract selected fields for every team
for team in standings:
    team_info = {
        "Team": team["teamName"]["default"],
        "Wins": team["wins"],
        "Losses": team["losses"],
        "Points": team["points"]
    }

    teams_data.append(team_info)

print(teams_data[0])

{'Team': 'Colorado Avalanche', 'Wins': 55, 'Losses': 16, 'Points': 121}

In [199]:
print(df.columns)

Index(['team_abbrev', 'team_name', 'conference_name', 'division_name',
       'logo_url'],
      dtype='str')

In [200]:
print(df.dtypes)

team_abbrev        str
team_name          str
conference_name    str
division_name      str
logo_url           str
dtype: object

In [201]:
# Find the team with the highest number of points
top_team = df.loc[df["Points"].idxmax()]

print(top_team)

KeyError: 'Points'

In [ ]:
# Sort all teams by Points from highest to lowest
top_5_teams = df.sort_values("Points", ascending=False).head(5)

print(top_5_teams)

                  Team  Wins  Losses  Points
0   Colorado Avalanche    55      16     121
1  Carolina Hurricanes    53      22     113
2         Dallas Stars    50      20     112
3       Buffalo Sabres    50      23     109
4  Tampa Bay Lightning    50      26     106

In [ ]:
# Find the team with the highest number of wins
top_wins_team = df.loc[df["Wins"].idxmax()]

print(top_wins_team)

Team      Colorado Avalanche
Wins                      55
Losses                    16
Points                   121
Name: 0, dtype: object

In [ ]:
# Find the team with the lowest number of wins
lowest_wins_team = df.loc[df["Wins"].idxmin()]

print(lowest_wins_team)

Team      Vancouver Canucks
Wins                     25
Losses                   49
Points                   58
Name: 31, dtype: object

In [ ]:
# Find the team with the highest number of losses
highest_losses_team = df.loc[df["Losses"].idxmax()]

print(highest_losses_team)

Team      Vancouver Canucks
Wins                     25
Losses                   49
Points                   58
Name: 31, dtype: object

In [ ]:
# Generate a statistical summary of the numerical columns
print(df.describe())

            Wins     Losses      Points
count  32.000000  32.000000   32.000000
mean   41.000000  30.812500   92.187500
std     6.810807   6.874157   13.177296
min    25.000000  16.000000   58.000000
25%    36.500000  26.000000   85.500000
50%    41.000000  30.500000   92.000000
75%    44.250000  35.250000   99.250000
max    55.000000  49.000000  121.000000

In [ ]:
# Calculate the average points of all NHL teams
average_points = df["Points"].mean()

print("Average Points:", average_points)

Average Points: 92.1875

In [ ]:
# Calculate the average number of wins across all NHL teams
average_wins = df["Wins"].mean()

print("Average Wins:", average_wins)

Average Wins: 41.0

In [ ]:
# Calculate the average number of losses across all NHL teams
average_losses = df["Losses"].mean()

print("Average Losses:", average_losses)

Average Losses: 30.8125

In [ ]:
# Round the average points to 2 decimal places for easier reading
print("Average Points:", round(average_points, 2))

Average Points: 92.19

In [ ]:
# Check for missing values in each column
print(df.isnull().sum())

Team      0
Wins      0
Losses    0
Points    0
dtype: int64

In [ ]:
# Check for duplicate team records
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
# Count the total number of teams in the DataFrame
print("Total Teams:", df["Team"].nunique())

Total Teams: 32

In [ ]:
# Rank all teams based on Points from highest to lowest
df["Rank"] = df["Points"].rank(method="min", ascending=False).astype(int)

print(df.sort_values("Rank").head(5))

                  Team  Wins  Losses  Points  Rank
0   Colorado Avalanche    55      16     121     1
1  Carolina Hurricanes    53      22     113     2
2         Dallas Stars    50      20     112     3
3       Buffalo Sabres    50      23     109     4
4  Tampa Bay Lightning    50      26     106     5

In [ ]:
# Display the first 5 rows with all columns
print(df.head())

                  Team  Wins  Losses  Points  Rank
0   Colorado Avalanche    55      16     121     1
1  Carolina Hurricanes    53      22     113     2
2         Dallas Stars    50      20     112     3
3       Buffalo Sabres    50      23     109     4
4  Tampa Bay Lightning    50      26     106     5

In [ ]:
rank_1_team = df[df["Rank"] == 1]

print(rank_1_team)

                 Team  Wins  Losses  Points  Rank
0  Colorado Avalanche    55      16     121     1

In [ ]:
data.keys()

dict_keys(['wildCardIndicator', 'standingsDateTimeUtc', 'standings'])

In [ ]:
standings_df = pd.DataFrame(data["standings"])

standings_df.head()

,clinchIndicator,conferenceAbbrev,conferenceHomeSequence,conferenceL10Sequence,conferenceName,conferenceRoadSequence,conferenceSequence,date,divisionAbbrev,divisionHomeSequence,...,teamName,teamCommonName,teamAbbrev,teamLogo,teamLogoDark,ties,waiversSequence,wildcardSequence,winPctg,wins
0,p,W,1,2,Western,1,1,2026-04-17,C,1,...,"{'default': 'Colorado Avalanche', 'fr': 'Avala...",{'default': 'Avalanche'},{'default': 'COL'},https://assets.nhle.com/logos/nhl/svg/COL_ligh...,https://assets.nhle.com/logos/nhl/svg/COL_dark...,0,32,0,0.670732,55
1,z,E,1,2,Eastern,3,1,2026-04-17,M,1,...,"{'default': 'Carolina Hurricanes', 'fr': 'Hurr...",{'default': 'Hurricanes'},{'default': 'CAR'},https://assets.nhle.com/logos/nhl/svg/CAR_ligh...,https://assets.nhle.com/logos/nhl/svg/CAR_dark...,0,31,0,0.646341,53
2,x,W,2,3,Western,2,2,2026-04-17,C,2,...,"{'default': 'Dallas Stars', 'fr': 'Stars de Da...",{'default': 'Stars'},{'default': 'DAL'},https://assets.nhle.com/logos/nhl/svg/DAL_ligh...,https://assets.nhle.com/logos/nhl/svg/DAL_dark...,0,30,0,0.609756,50
3,y,E,3,6,Eastern,4,2,2026-04-17,A,2,...,"{'default': 'Buffalo Sabres', 'fr': 'Sabres de...",{'default': 'Sabres'},{'default': 'BUF'},https://assets.nhle.com/logos/nhl/svg/BUF_ligh...,https://assets.nhle.com/logos/nhl/svg/BUF_dark...,0,29,0,0.609756,50
4,x,E,5,12,Eastern,2,3,2026-04-17,A,3,...,"{'default': 'Tampa Bay Lightning', 'fr': 'Ligh...",{'default': 'Lightning'},{'default': 'TBL'},https://assets.nhle.com/logos/nhl/svg/TBL_ligh...,https://assets.nhle.com/logos/nhl/svg/TBL_dark...,0,28,0,0.609756,50

In [ ]:
standings_df.columns.tolist()

['clinchIndicator',
 'conferenceAbbrev',
 'conferenceHomeSequence',
 'conferenceL10Sequence',
 'conferenceName',
 'conferenceRoadSequence',
 'conferenceSequence',
 'date',
 'divisionAbbrev',
 'divisionHomeSequence',
 'divisionL10Sequence',
 'divisionName',
 'divisionRoadSequence',
 'divisionSequence',
 'gameTypeId',
 'gamesPlayed',
 'goalDifferential',
 'goalDifferentialPctg',
 'goalAgainst',
 'goalFor',
 'goalsForPctg',
 'homeGamesPlayed',
 'homeGoalDifferential',
 'homeGoalsAgainst',
 'homeGoalsFor',
 'homeLosses',
 'homeOtLosses',
 'homePoints',
 'homeRegulationPlusOtWins',
 'homeRegulationWins',
 'homeTies',
 'homeWins',
 'l10GamesPlayed',
 'l10GoalDifferential',
 'l10GoalsAgainst',
 'l10GoalsFor',
 'l10Losses',
 'l10OtLosses',
 'l10Points',
 'l10RegulationPlusOtWins',
 'l10RegulationWins',
 'l10Ties',
 'l10Wins',
 'leagueHomeSequence',
 'leagueL10Sequence',
 'leagueRoadSequence',
 'leagueSequence',
 'losses',
 'otLosses',
 'placeName',
 'pointPctg',
 'points',
 'regulationPlusOtWinPctg',
 'regulationPlusOtWins',
 'regulationWinPctg',
 'regulationWins',
 'roadGamesPlayed',
 'roadGoalDifferential',
 'roadGoalsAgainst',
 'roadGoalsFor',
 'roadLosses',
 'roadOtLosses',
 'roadPoints',
 'roadRegulationPlusOtWins',
 'roadRegulationWins',
 'roadTies',
 'roadWins',
 'seasonId',
 'shootoutLosses',
 'shootoutWins',
 'streakCode',
 'streakCount',
 'teamName',
 'teamCommonName',
 'teamAbbrev',
 'teamLogo',
 'teamLogoDark',
 'ties',
 'waiversSequence',
 'wildcardSequence',
 'winPctg',
 'wins']

In [ ]:
for i, col in enumerate(standings_df.columns, start=1):
    print(i, col)

1 clinchIndicator
2 conferenceAbbrev
3 conferenceHomeSequence
4 conferenceL10Sequence
5 conferenceName
6 conferenceRoadSequence
7 conferenceSequence
8 date
9 divisionAbbrev
10 divisionHomeSequence
11 divisionL10Sequence
12 divisionName
13 divisionRoadSequence
14 divisionSequence
15 gameTypeId
16 gamesPlayed
17 goalDifferential
18 goalDifferentialPctg
19 goalAgainst
20 goalFor
21 goalsForPctg
22 homeGamesPlayed
23 homeGoalDifferential
24 homeGoalsAgainst
25 homeGoalsFor
26 homeLosses
27 homeOtLosses
28 homePoints
29 homeRegulationPlusOtWins
30 homeRegulationWins
31 homeTies
32 homeWins
33 l10GamesPlayed
34 l10GoalDifferential
35 l10GoalsAgainst
36 l10GoalsFor
37 l10Losses
38 l10OtLosses
39 l10Points
40 l10RegulationPlusOtWins
41 l10RegulationWins
42 l10Ties
43 l10Wins
44 leagueHomeSequence
45 leagueL10Sequence
46 leagueRoadSequence
47 leagueSequence
48 losses
49 otLosses
50 placeName
51 pointPctg
52 points
53 regulationPlusOtWinPctg
54 regulationPlusOtWins
55 regulationWinPctg
56 regulationWins
57 roadGamesPlayed
58 roadGoalDifferential
59 roadGoalsAgainst
60 roadGoalsFor
61 roadLosses
62 roadOtLosses
63 roadPoints
64 roadRegulationPlusOtWins
65 roadRegulationWins
66 roadTies
67 roadWins
68 seasonId
69 shootoutLosses
70 shootoutWins
71 streakCode
72 streakCount
73 teamName
74 teamCommonName
75 teamAbbrev
76 teamLogo
77 teamLogoDark
78 ties
79 waiversSequence
80 wildcardSequence
81 winPctg
82 wins

In [ ]:
required_columns = [
    "teamAbbrev",
    "teamName",
    "conferenceName",
    "divisionName",
    "teamLogo",
    "gamesPlayed",
    "wins",
    "losses",
    "otLosses",
    "points",
    "goalFor",
    "goalAgainst"
]

standings_df[required_columns].head()

,teamAbbrev,teamName,conferenceName,divisionName,teamLogo,gamesPlayed,wins,losses,otLosses,points,goalFor,goalAgainst
0,{'default': 'COL'},"{'default': 'Colorado Avalanche', 'fr': 'Avala...",Western,Central,https://assets.nhle.com/logos/nhl/svg/COL_ligh...,82,55,16,11,121,302,203
1,{'default': 'CAR'},"{'default': 'Carolina Hurricanes', 'fr': 'Hurr...",Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/CAR_ligh...,82,53,22,7,113,296,240
2,{'default': 'DAL'},"{'default': 'Dallas Stars', 'fr': 'Stars de Da...",Western,Central,https://assets.nhle.com/logos/nhl/svg/DAL_ligh...,82,50,20,12,112,279,226
3,{'default': 'BUF'},"{'default': 'Buffalo Sabres', 'fr': 'Sabres de...",Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/BUF_ligh...,82,50,23,9,109,288,241
4,{'default': 'TBL'},"{'default': 'Tampa Bay Lightning', 'fr': 'Ligh...",Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/TBL_ligh...,82,50,26,6,106,290,231

In [ ]:
standings_df["team_abbrev"] = standings_df["teamAbbrev"].apply(lambda x: x["default"])
standings_df["team_name"] = standings_df["teamName"].apply(lambda x: x["default"])

In [ ]:
standings_df[["team_abbrev", "team_name"]].head()

  team_abbrev            team_name
0         COL   Colorado Avalanche
1         CAR  Carolina Hurricanes
2         DAL         Dallas Stars
3         BUF       Buffalo Sabres
4         TBL  Tampa Bay Lightning

In [ ]:
type(standings_df["teamLogo"].iloc[0])

str

In [ ]:
standings_df["teamLogo"].iloc[0]

'https://assets.nhle.com/logos/nhl/svg/COL_light.svg'

In [ ]:
standings_df["logo_url"] = standings_df["teamLogo"].str.extract(r"\((.*?)\)")

In [ ]:
standings_df["logo_url"] = standings_df["teamLogo"].apply(
    lambda x: x.split("(")[1].split(")")[0] if isinstance(x, str) and "(" in x else None
)

standings_df[["team_abbrev", "team_name", "logo_url"]].head()

  team_abbrev            team_name logo_url
0         COL   Colorado Avalanche     None
1         CAR  Carolina Hurricanes     None
2         DAL         Dallas Stars     None
3         BUF       Buffalo Sabres     None
4         TBL  Tampa Bay Lightning     None

In [ ]:
standings_df["teamLogo"].iloc[0]

'https://assets.nhle.com/logos/nhl/svg/COL_light.svg'

In [ ]:
standings_df["logo_url"] = standings_df["teamLogo"].apply(
    lambda x: x.split("(")[1].split(")")[0] if isinstance(x, str) and "(" in x else None
)

standings_df[["team_abbrev", "team_name", "logo_url"]].head()

  team_abbrev            team_name logo_url
0         COL   Colorado Avalanche     None
1         CAR  Carolina Hurricanes     None
2         DAL         Dallas Stars     None
3         BUF       Buffalo Sabres     None
4         TBL  Tampa Bay Lightning     None

In [ ]:
# Check the actual values stored in the teamLogo column
standings_df["teamLogo"].head()

0    https://assets.nhle.com/logos/nhl/svg/COL_ligh...
1    https://assets.nhle.com/logos/nhl/svg/CAR_ligh...
2    https://assets.nhle.com/logos/nhl/svg/DAL_ligh...
3    https://assets.nhle.com/logos/nhl/svg/BUF_ligh...
4    https://assets.nhle.com/logos/nhl/svg/TBL_ligh...
Name: teamLogo, dtype: str

In [ ]:
# Display the data type of the first teamLogo value
print(type(standings_df["teamLogo"].iloc[0]))

print(standings_df["teamLogo"].iloc[0])

<class 'str'>
https://assets.nhle.com/logos/nhl/svg/COL_light.svg

In [ ]:
# Copy the existing NHL team logo URL into the logo_url column
standings_df["logo_url"] = standings_df["teamLogo"]

standings_df[["team_abbrev", "team_name", "logo_url"]].head()

,team_abbrev,team_name,logo_url
0,COL,Colorado Avalanche,https://assets.nhle.com/logos/nhl/svg/COL_ligh...
1,CAR,Carolina Hurricanes,https://assets.nhle.com/logos/nhl/svg/CAR_ligh...
2,DAL,Dallas Stars,https://assets.nhle.com/logos/nhl/svg/DAL_ligh...
3,BUF,Buffalo Sabres,https://assets.nhle.com/logos/nhl/svg/BUF_ligh...
4,TBL,Tampa Bay Lightning,https://assets.nhle.com/logos/nhl/svg/TBL_ligh...

In [ ]:
# Count missing logo URLs
print("Missing logo URLs:", standings_df["logo_url"].isna().sum())

print("Total teams:", standings_df["team_abbrev"].nunique())

Missing logo URLs: 0
Total teams: 32

In [ ]:
# Check the team dataset structure
df.info()

print("Total teams:", len(df))
print("Duplicate teams:", df["Team"].duplicated().sum())
display(df)

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Team    32 non-null     str
 1   Wins    32 non-null     int64
 2   Losses  32 non-null     int64
 3   Points  32 non-null     int64
 4   Rank    32 non-null     int64
dtypes: int64(4), str(1)
memory usage: 1.4 KB
Total teams: 32
Duplicate teams: 0

                     Team  Wins  Losses  Points  Rank
0      Colorado Avalanche    55      16     121     1
1     Carolina Hurricanes    53      22     113     2
2            Dallas Stars    50      20     112     3
3          Buffalo Sabres    50      23     109     4
4     Tampa Bay Lightning    50      26     106     5
5      Montréal Canadiens    48      24     106     5
6          Minnesota Wild    46      24     104     7
7           Boston Bruins    45      27     100     8
8         Ottawa Senators    44      27      99     9
9     Pittsburgh Penguins    41      25      98    10
10    Philadelphia Flyers    43      27      98    10
11    Washington Capitals    43      30      95    12
12   Vegas Golden Knights    39      26      95    12
13        Edmonton Oilers    41      30      93    14
14           Utah Mammoth    43      33      92    15
15      Detroit Red Wings    41      31      92    15
16  Columbus Blue Jackets    40      30      92    15
17          Anaheim Ducks    43      33      92    15
18     New York Islanders    43      34      91    19
19      Los Angeles Kings    35      27      90    20
20      New Jersey Devils    42      37      87    21
21        St. Louis Blues    37      33      86    22
22    Nashville Predators    38      34      86    22
23        San Jose Sharks    39      35      86    22
24       Florida Panthers    40      38      84    25
25          Winnipeg Jets    35      35      82    26
26         Seattle Kraken    34      37      79    27
27    Toronto Maple Leafs    32      36      78    28
28         Calgary Flames    34      39      77    29
29       New York Rangers    34      39      77    29
30     Chicago Blackhawks    29      39      72    31
31      Vancouver Canucks    25      49      58    32

In [ ]:
# Check for negative values in numeric columns
print("Negative Wins:", (df["Wins"] < 0).sum())
print("Negative Losses:", (df["Losses"] < 0).sum())
print("Negative Points:", (df["Points"] < 0).sum())
print("Negative Rank:", (df["Rank"] < 0).sum())

Negative Wins: 0
Negative Losses: 0
Negative Points: 0
Negative Rank: 0

In [ ]:
# Check the structure of the raw API data
type(data)

dict

In [ ]:
# Display the keys available in the API response
data.keys()

dict_keys(['wildCardIndicator', 'standingsDateTimeUtc', 'standings'])

In [ ]:
# Inspect one team record from the NHL standings API response
data["standings"][0]

{'clinchIndicator': 'p',
 'conferenceAbbrev': 'W',
 'conferenceHomeSequence': 1,
 'conferenceL10Sequence': 2,
 'conferenceName': 'Western',
 'conferenceRoadSequence': 1,
 'conferenceSequence': 1,
 'date': '2026-04-17',
 'divisionAbbrev': 'C',
 'divisionHomeSequence': 1,
 'divisionL10Sequence': 1,
 'divisionName': 'Central',
 'divisionRoadSequence': 1,
 'divisionSequence': 1,
 'gameTypeId': 2,
 'gamesPlayed': 82,
 'goalDifferential': 99,
 'goalDifferentialPctg': 1.207317,
 'goalAgainst': 203,
 'goalFor': 302,
 'goalsForPctg': 3.682927,
 'homeGamesPlayed': 41,
 'homeGoalDifferential': 49,
 'homeGoalsAgainst': 108,
 'homeGoalsFor': 157,
 'homeLosses': 9,
 'homeOtLosses': 6,
 'homePoints': 58,
 'homeRegulationPlusOtWins': 25,
 'homeRegulationWins': 25,
 'homeTies': 0,
 'homeWins': 26,
 'l10GamesPlayed': 10,
 'l10GoalDifferential': 14,
 'l10GoalsAgainst': 20,
 'l10GoalsFor': 34,
 'l10Losses': 2,
 'l10OtLosses': 1,
 'l10Points': 15,
 'l10RegulationPlusOtWins': 6,
 'l10RegulationWins': 6,
 'l10Ties': 0,
 'l10Wins': 7,
 'leagueHomeSequence': 3,
 'leagueL10Sequence': 4,
 'leagueRoadSequence': 1,
 'leagueSequence': 1,
 'losses': 16,
 'otLosses': 11,
 'placeName': {'default': 'Colorado'},
 'pointPctg': 0.737805,
 'points': 121,
 'regulationPlusOtWinPctg': 0.621951,
 'regulationPlusOtWins': 51,
 'regulationWinPctg': 0.585366,
 'regulationWins': 48,
 'roadGamesPlayed': 41,
 'roadGoalDifferential': 50,
 'roadGoalsAgainst': 95,
 'roadGoalsFor': 145,
 'roadLosses': 7,
 'roadOtLosses': 5,
 'roadPoints': 63,
 'roadRegulationPlusOtWins': 26,
 'roadRegulationWins': 23,
 'roadTies': 0,
 'roadWins': 29,
 'seasonId': 20252026,
 'shootoutLosses': 6,
 'shootoutWins': 4,
 'streakCode': 'W',
 'streakCount': 3,
 'teamName': {'default': 'Colorado Avalanche', 'fr': 'Avalanche du Colorado'},
 'teamCommonName': {'default': 'Avalanche'},
 'teamAbbrev': {'default': 'COL'},
 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg',
 'teamLogoDark': 'https://assets.nhle.com/logos/nhl/svg/COL_dark.svg',
 'ties': 0,
 'waiversSequence': 32,
 'wildcardSequence': 0,
 'winPctg': 0.670732,
 'wins': 55}

In [ ]:
# Display all field names available in one NHL standings record
print(data["standings"][0].keys())

dict_keys(['clinchIndicator', 'conferenceAbbrev', 'conferenceHomeSequence', 'conferenceL10Sequence', 'conferenceName', 'conferenceRoadSequence', 'conferenceSequence', 'date', 'divisionAbbrev', 'divisionHomeSequence', 'divisionL10Sequence', 'divisionName', 'divisionRoadSequence', 'divisionSequence', 'gameTypeId', 'gamesPlayed', 'goalDifferential', 'goalDifferentialPctg', 'goalAgainst', 'goalFor', 'goalsForPctg', 'homeGamesPlayed', 'homeGoalDifferential', 'homeGoalsAgainst', 'homeGoalsFor', 'homeLosses', 'homeOtLosses', 'homePoints', 'homeRegulationPlusOtWins', 'homeRegulationWins', 'homeTies', 'homeWins', 'l10GamesPlayed', 'l10GoalDifferential', 'l10GoalsAgainst', 'l10GoalsFor', 'l10Losses', 'l10OtLosses', 'l10Points', 'l10RegulationPlusOtWins', 'l10RegulationWins', 'l10Ties', 'l10Wins', 'leagueHomeSequence', 'leagueL10Sequence', 'leagueRoadSequence', 'leagueSequence', 'losses', 'otLosses', 'placeName', 'pointPctg', 'points', 'regulationPlusOtWinPctg', 'regulationPlusOtWins', 'regulationWinPctg', 'regulationWins', 'roadGamesPlayed', 'roadGoalDifferential', 'roadGoalsAgainst', 'roadGoalsFor', 'roadLosses', 'roadOtLosses', 'roadPoints', 'roadRegulationPlusOtWins', 'roadRegulationWins', 'roadTies', 'roadWins', 'seasonId', 'shootoutLosses', 'shootoutWins', 'streakCode', 'streakCount', 'teamName', 'teamCommonName', 'teamAbbrev', 'teamLogo', 'teamLogoDark', 'ties', 'waiversSequence', 'wildcardSequence', 'winPctg', 'wins'])

In [ ]:
# Extract and normalize team information for the teams table
teams_data = []

for team in data["standings"]:
    teams_data.append({
        "team_abbrev": team["teamAbbrev"]["default"],
        "team_name": team["teamName"]["default"],
        "conference_name": team["conferenceName"],
        "division_name": team["divisionName"],
        "logo_url": team["teamLogo"]
    })

# Convert the extracted data into a DataFrame
teams_df = pd.DataFrame(teams_data)

# Display the cleaned teams dataset
display(teams_df)

,team_abbrev,team_name,conference_name,division_name,logo_url
0,COL,Colorado Avalanche,Western,Central,https://assets.nhle.com/logos/nhl/svg/COL_ligh...
1,CAR,Carolina Hurricanes,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/CAR_ligh...
2,DAL,Dallas Stars,Western,Central,https://assets.nhle.com/logos/nhl/svg/DAL_ligh...
3,BUF,Buffalo Sabres,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/BUF_ligh...
4,TBL,Tampa Bay Lightning,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/TBL_ligh...
5,MTL,Montréal Canadiens,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...
6,MIN,Minnesota Wild,Western,Central,https://assets.nhle.com/logos/nhl/svg/MIN_ligh...
7,BOS,Boston Bruins,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/BOS_ligh...
8,OTT,Ottawa Senators,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/OTT_ligh...
9,PIT,Pittsburgh Penguins,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/PIT_ligh...
10,PHI,Philadelphia Flyers,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/PHI_ligh...
11,WSH,Washington Capitals,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/WSH_seco...
12,VGK,Vegas Golden Knights,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/VGK_ligh...
13,EDM,Edmonton Oilers,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/EDM_ligh...
14,UTA,Utah Mammoth,Western,Central,https://assets.nhle.com/logos/nhl/svg/UTA_ligh...
15,DET,Detroit Red Wings,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/DET_ligh...
16,CBJ,Columbus Blue Jackets,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/CBJ_ligh...
17,ANA,Anaheim Ducks,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/ANA_ligh...
18,NYI,New York Islanders,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/NYI_ligh...
19,LAK,Los Angeles Kings,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/LAK_ligh...
20,NJD,New Jersey Devils,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/NJD_ligh...
21,STL,St. Louis Blues,Western,Central,https://assets.nhle.com/logos/nhl/svg/STL_ligh...
22,NSH,Nashville Predators,Western,Central,https://assets.nhle.com/logos/nhl/svg/NSH_ligh...
23,SJS,San Jose Sharks,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/SJS_ligh...
24,FLA,Florida Panthers,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/FLA_ligh...
25,WPG,Winnipeg Jets,Western,Central,https://assets.nhle.com/logos/nhl/svg/WPG_ligh...
26,SEA,Seattle Kraken,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/SEA_ligh...
27,TOR,Toronto Maple Leafs,Eastern,Atlantic,https://assets.nhle.com/logos/nhl/svg/TOR_ligh...
28,CGY,Calgary Flames,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/CGY_ligh...
29,NYR,New York Rangers,Eastern,Metropolitan,https://assets.nhle.com/logos/nhl/svg/NYR_ligh...
30,CHI,Chicago Blackhawks,Western,Central,https://assets.nhle.com/logos/nhl/svg/CHI_ligh...
31,VAN,Vancouver Canucks,Western,Pacific,https://assets.nhle.com/logos/nhl/svg/VAN_ligh...

In [ ]:
# Validate the cleaned teams dataset
print("Total teams:", len(teams_df))

print("\nMissing values:")
print(teams_df.isnull().sum())

print("\nDuplicate team abbreviations:",
      teams_df["team_abbrev"].duplicated().sum())

print("\nMissing logo URLs:",
      teams_df["logo_url"].isnull().sum())

Total teams: 32

Missing values:
team_abbrev        0
team_name          0
conference_name    0
division_name      0
logo_url           0
dtype: int64

Duplicate team abbreviations: 0

Missing logo URLs: 0

In [ ]:
# Extract required standings information from the NHL API response
standings_data = []

for team in data["standings"]:
    standings_data.append({
        "team_abbrev": team["teamAbbrev"]["default"],
        "season": str(team["seasonId"]),
        "games_played": team["gamesPlayed"],
        "wins": team["wins"],
        "losses": team["losses"],
        "ot_losses": team["otLosses"],
        "points": team["points"],
        "goals_for": team["goalFor"],
        "goals_against": team["goalAgainst"],
        "home_wins": team["homeWins"],
        "away_wins": team["roadWins"],
        "streak_type": team["streakCode"],
        "streak_count": team["streakCount"]
    })

# Convert the extracted standings data into a DataFrame
standings_df = pd.DataFrame(standings_data)

# Display the standings dataset
display(standings_df)

,team_abbrev,season,games_played,wins,losses,ot_losses,points,goals_for,goals_against,home_wins,away_wins,streak_type,streak_count
0,COL,20252026,82,55,16,11,121,302,203,26,29,W,3
1,CAR,20252026,82,53,22,7,113,296,240,29,24,W,1
2,DAL,20252026,82,50,20,12,112,279,226,26,24,W,5
3,BUF,20252026,82,50,23,9,109,288,241,26,24,OT,1
4,TBL,20252026,82,50,26,6,106,290,231,26,24,L,1
5,MTL,20252026,82,48,24,10,106,283,256,24,24,L,1
6,MIN,20252026,82,46,24,12,104,272,240,23,23,W,1
7,BOS,20252026,82,45,27,10,100,272,250,29,16,W,2
8,OTT,20252026,82,44,27,11,99,278,246,23,21,W,1
9,PIT,20252026,82,41,25,16,98,293,268,20,21,L,3
10,PHI,20252026,82,43,27,12,98,250,243,20,23,W,3
11,WSH,20252026,82,43,30,9,95,263,244,25,18,W,4
12,VGK,20252026,82,39,26,17,95,265,250,20,19,W,3
13,EDM,20252026,82,41,30,11,93,282,269,22,19,W,1
14,UTA,20252026,82,43,33,6,92,268,240,22,21,L,1
15,DET,20252026,82,41,31,10,92,241,258,21,20,L,1
16,CBJ,20252026,82,40,30,12,92,253,253,20,20,L,2
17,ANA,20252026,82,43,33,6,92,273,288,24,19,W,1
18,NYI,20252026,82,43,34,5,91,233,241,22,21,L,3
19,LAK,20252026,82,35,27,20,90,225,247,15,20,L,1
20,NJD,20252026,82,42,37,3,87,230,254,21,21,L,1
21,STL,20252026,82,37,33,12,86,231,258,20,17,W,4
22,NSH,20252026,82,38,34,10,86,247,269,21,17,L,2
23,SJS,20252026,82,39,35,8,86,251,292,21,18,W,1
24,FLA,20252026,82,40,38,4,84,251,276,23,17,W,3
25,WPG,20252026,82,35,35,12,82,231,260,19,16,L,4
26,SEA,20252026,82,34,37,11,79,226,263,19,15,L,3
27,TOR,20252026,82,32,36,14,78,253,299,18,14,L,5
28,CGY,20252026,82,34,39,9,77,212,259,23,11,W,1
29,NYR,20252026,82,34,39,9,77,238,250,14,20,W,1
30,CHI,20252026,82,29,39,14,72,213,275,14,15,W,1
31,VAN,20252026,82,25,49,8,58,216,316,9,16,L,1

In [ ]:
# Validate the standings dataset
print("Total standings records:", len(standings_df))

print("\nMissing values:")
print(standings_df.isnull().sum())

print("\nDuplicate team abbreviations:",
      standings_df["team_abbrev"].duplicated().sum())

print("\nNegative values check:")

numeric_columns = [
    "games_played",
    "wins",
    "losses",
    "ot_losses",
    "points",
    "goals_for",
    "goals_against",
    "home_wins",
    "away_wins",
    "streak_count"
]

for column in numeric_columns:
    print(f"{column}: {(standings_df[column] < 0).sum()}")

Total standings records: 32

Missing values:
team_abbrev      0
season           0
games_played     0
wins             0
losses           0
ot_losses        0
points           0
goals_for        0
goals_against    0
home_wins        0
away_wins        0
streak_type      0
streak_count     0
dtype: int64

Duplicate team abbreviations: 0

Negative values check:
games_played: 0
wins: 0
losses: 0
ot_losses: 0
points: 0
goals_for: 0
goals_against: 0
home_wins: 0
away_wins: 0
streak_count: 0

In [ ]:
import requests

# Fetch the current roster for Colorado Avalanche
team_abbrev = "COL"

roster_url = f"https://api-web.nhle.com/v1/roster/{team_abbrev}/current"
roster_response = requests.get(roster_url)
print("Status code:", roster_response.status_code)
roster_data = roster_response.json()
print("Response keys:", roster_data.keys())

Status code: 200
Response keys: dict_keys(['forwards', 'defensemen', 'goalies'])

In [ ]:
# Inspect the first forward player to understand the roster data structure
first_forward = roster_data["forwards"][0]

# Display the available fields for the player
print("Player fields:")
print(first_forward.keys())
print("\nFirst player record:")
print(first_forward)

Player fields:
dict_keys(['id', 'headshot', 'firstName', 'lastName', 'positionCode', 'shootsCatches', 'heightInInches', 'weightInPounds', 'heightInCentimeters', 'weightInKilograms', 'birthDate', 'birthCity', 'birthCountry', 'birthStateProvince'])

First player record:
{'id': 8481550, 'headshot': 'https://assets.nhle.com/mugs/nhl/20262027/COL/8481550.png', 'firstName': {'default': 'Adam'}, 'lastName': {'default': 'Beckman'}, 'positionCode': 'L', 'shootsCatches': 'L', 'heightInInches': 74, 'weightInPounds': 192, 'heightInCentimeters': 188, 'weightInKilograms': 87, 'birthDate': '2001-05-10', 'birthCity': {'default': 'Saskatoon'}, 'birthCountry': 'CAN', 'birthStateProvince': {'default': 'SK'}}

In [ ]:
# Check the number of players in each roster category
print("Forwards:", len(roster_data["forwards"]))
print("Defensemen:", len(roster_data["defensemen"]))
print("Goalies:", len(roster_data["goalies"]))

# Inspect the first defenseman record
print("\nFirst defenseman:")
print(roster_data["defensemen"][0])

# Inspect the first goalie record
print("\nFirst goalie:")
print(roster_data["goalies"][0])

Forwards: 22
Defensemen: 15
Goalies: 5

First defenseman:
{'id': 8483569, 'headshot': 'https://assets.nhle.com/mugs/nhl/20262027/COL/8483569.png', 'firstName': {'default': 'Wyatt'}, 'lastName': {'default': 'Aamodt'}, 'sweaterNumber': 5, 'positionCode': 'D', 'shootsCatches': 'L', 'heightInInches': 72, 'weightInPounds': 201, 'heightInCentimeters': 183, 'weightInKilograms': 91, 'birthDate': '1997-11-22', 'birthCity': {'default': 'Hermantown'}, 'birthCountry': 'USA', 'birthStateProvince': {'default': 'MN'}}

First goalie:
{'id': 8478406, 'headshot': 'https://assets.nhle.com/mugs/nhl/20262027/COL/8478406.png', 'firstName': {'default': 'Mackenzie'}, 'lastName': {'default': 'Blackwood'}, 'sweaterNumber': 39, 'positionCode': 'G', 'shootsCatches': 'L', 'heightInInches': 76, 'weightInPounds': 225, 'heightInCentimeters': 193, 'weightInKilograms': 102, 'birthDate': '1996-12-09', 'birthCity': {'default': 'Thunder Bay'}, 'birthCountry': 'CAN', 'birthStateProvince': {'default': 'ON'}}

In [ ]:
# Combine forwards, defensemen, and goalies into one player list
all_players = (
    roster_data["forwards"]
    + roster_data["defensemen"]
    + roster_data["goalies"]
)

# Extract the required player information for the players table
players_data = []

for player in all_players:
    players_data.append({
        "player_id": player["id"],
        "first_name": player["firstName"]["default"],
        "last_name": player["lastName"]["default"],
        "position": player["positionCode"],
        "jersey_number": player.get("sweaterNumber"),
        "birth_date": player.get("birthDate"),
        "birth_country": player.get("birthCountry"),
        "height_cm": player.get("heightInCentimeters"),
        "weight_kg": player.get("weightInKilograms"),
        "shoots_catches": player.get("shootsCatches"),
        "headshot_url": player.get("headshot")
    })

# Convert the extracted player data into a DataFrame
players_df = pd.DataFrame(players_data)

# Display the players dataset
display(players_df)

,player_id,first_name,last_name,position,jersey_number,birth_date,birth_country,height_cm,weight_kg,shoots_catches,headshot_url
0,8481550,Adam,Beckman,L,NaN,2001-05-10,CAN,188,87,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
1,8484149,Gavin,Brindley,C,54.0,2004-10-05,USA,173,78,R,https://assets.nhle.com/mugs/nhl/20262027/COL/...
2,8486151,Matthew,DiMarsico,C,NaN,2004-01-07,USA,183,82,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
3,8485474,Cooper,Gay,R,NaN,2002-03-15,USA,193,95,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
4,8476994,Vinnie,Hinostroza,C,NaN,1994-04-03,USA,178,83,R,https://assets.nhle.com/mugs/nhl/20262027/COL/...
5,8486171,T.J.,Hughes,R,NaN,2001-11-09,CAN,183,84,NaN,https://assets.nhle.com/mugs/nhl/20262027/COL/...
6,8475172,Nazem,Kadri,C,91.0,1990-10-06,CAN,183,84,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
7,8480448,Parker,Kelly,C,17.0,1999-05-14,CAN,185,84,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
8,8482742,Zachary,L'Heureux,L,NaN,2003-05-15,CAN,180,89,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
9,8476455,Gabriel,Landeskog,L,92.0,1992-11-23,SWE,185,98,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
10,8477476,Artturi,Lehkonen,L,62.0,1995-07-04,FIN,180,81,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
11,8482763,Fabian,Lysell,R,NaN,2003-01-19,SWE,180,84,R,https://assets.nhle.com/mugs/nhl/20262027/COL/...
12,8477492,Nathan,MacKinnon,C,29.0,1995-09-01,CAN,183,91,R,https://assets.nhle.com/mugs/nhl/20262027/COL/...
13,8482953,Taylor,Makar,L,16.0,2001-03-13,CAN,191,86,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
14,8483567,Georgii,Merkulov,C,NaN,2000-10-10,RUS,180,79,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
15,8480039,Martin,Necas,C,88.0,1999-01-15,CZE,191,88,R,https://assets.nhle.com/mugs/nhl/20262027/COL/...
16,8475754,Brock,Nelson,C,11.0,1991-10-15,USA,193,93,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
17,8481186,Logan,O'Connor,R,25.0,1996-08-14,USA,183,79,R,https://assets.nhle.com/mugs/nhl/20262027/COL/...
18,8485105,Nikita,Prishchepov,C,85.0,2004-02-20,RUS,185,88,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
19,8478462,Nicolas,Roy,C,10.0,1997-02-05,CAN,193,91,R,https://assets.nhle.com/mugs/nhl/20262027/COL/...
20,8475768,Jaden,Schwartz,C,NaN,1992-06-25,CAN,178,84,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
21,8482768,Fedor,Svechkov,C,NaN,2003-04-05,RUS,183,85,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
22,8483569,Wyatt,Aamodt,D,5.0,1997-11-22,USA,183,91,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
23,8482676,Sean,Behrens,D,2.0,2003-03-31,USA,178,80,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
24,8470613,Brent,Burns,D,84.0,1985-03-09,CAN,196,103,R,https://assets.nhle.com/mugs/nhl/20262027/COL/...
25,8481562,Domenick,Fensore,D,NaN,2001-09-07,USA,175,79,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
26,8482942,Alex,Gagne,D,45.0,2002-08-12,USA,193,93,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
27,8478454,Noah,Juulsen,D,NaN,1997-04-02,CAN,188,91,R,https://assets.nhle.com/mugs/nhl/20262027/COL/...
28,8476967,Brett,Kulak,D,27.0,1994-01-06,CAN,185,87,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
29,8480069,Cale,Makar,D,8.0,1998-10-30,CAN,183,85,R,https://assets.nhle.com/mugs/nhl/20262027/COL/...
30,8484258,Sam,Malinski,D,70.0,1998-07-27,USA,180,86,R,https://assets.nhle.com/mugs/nhl/20262027/COL/...
31,8476312,Josh,Manson,D,42.0,1991-10-07,USA,191,99,R,https://assets.nhle.com/mugs/nhl/20262027/COL/...
32,8479387,Keaton,Middleton,D,67.0,1998-02-10,CAN,198,109,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
33,8486118,Gustav,Stjernberg,D,NaN,2002-10-12,SWE,193,95,R,https://assets.nhle.com/mugs/nhl/20262027/COL/...
34,8478038,Devon,Toews,D,7.0,1994-02-21,CAN,185,87,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
35,8484556,Saige,Weinstein,D,89.0,2005-05-30,CAN,185,84,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
36,8478846,Christian,Wolanin,D,NaN,1995-03-17,CAN,188,86,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
37,8478406,Mackenzie,Blackwood,G,39.0,1996-12-09,CAN,193,102,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
38,8481529,Trent,Miner,G,50.0,2001-02-05,CAN,185,84,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
39,8484996,Ilya,Nabokov,G,NaN,2003-03-27,RUS,183,81,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
40,8486206,Nikita,Novosyolov,G,NaN,2004-06-03,RUS,188,78,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...
41,8475809,Scott,Wedgewood,G,41.0,1992-08-14,CAN,188,91,L,https://assets.nhle.com/mugs/nhl/20262027/COL/...

In [ ]:
# Validate the Colorado Avalanche players dataset
print("Total players:", len(players_df))

print("\nMissing values:")
print(players_df.isnull().sum())

print("\nDuplicate player IDs:",
      players_df["player_id"].duplicated().sum())

print("\nUnique positions:")
print(players_df["position"].value_counts())

Total players: 42

Missing values:
player_id          0
first_name         0
last_name          0
position           0
jersey_number     16
birth_date         0
birth_country      0
height_cm          0
weight_kg          0
shoots_catches     1
headshot_url       0
dtype: int64

Duplicate player IDs: 0

Unique positions:
position
D    15
C    13
L     5
G     5
R     4
Name: count, dtype: int64

In [ ]:
import time
import requests

# Create an empty list to store players from all NHL teams
all_players_data = []

# Fetch the current roster for every team
for team_abbrev in teams_df["team_abbrev"]:

    # Build the roster API URL for the current team
    roster_url = f"https://api-web.nhle.com/v1/roster/{team_abbrev}/current"

    # Send the API request
    response = requests.get(roster_url)

    # Check whether the API request was successful
    if response.status_code == 200:

        # Convert the API response into a Python dictionary
        roster = response.json()

        # Combine all player categories
        players = (
            roster.get("forwards", [])
            + roster.get("defensemen", [])
            + roster.get("goalies", [])
        )

        # Extract required player information
        for player in players:
            all_players_data.append({
                "team_abbrev": team_abbrev,
                "player_id": player["id"],
                "first_name": player["firstName"]["default"],
                "last_name": player["lastName"]["default"],
                "position": player["positionCode"],
                "jersey_number": player.get("sweaterNumber"),
                "birth_date": player.get("birthDate"),
                "birth_country": player.get("birthCountry"),
                "height_cm": player.get("heightInCentimeters"),
                "weight_kg": player.get("weightInKilograms"),
                "shoots_catches": player.get("shootsCatches"),
                "headshot_url": player.get("headshot")
            })

        print(f"{team_abbrev}: {len(players)} players fetched")

    else:
        print(f"{team_abbrev}: API request failed - {response.status_code}")

    # Add a small delay between API requests
    time.sleep(0.5)

# Convert all collected player records into a DataFrame
players_df = pd.DataFrame(all_players_data)

# Display the total number of collected players
print("\nTotal players collected:", len(players_df))

COL: 42 players fetched
CAR: 43 players fetched
DAL: 43 players fetched
BUF: 44 players fetched
TBL: 49 players fetched
MTL: 42 players fetched
MIN: 45 players fetched
BOS: 42 players fetched
OTT: 27 players fetched
PIT: 23 players fetched
PHI: 44 players fetched
WSH: 25 players fetched
VGK: 36 players fetched
EDM: 45 players fetched
UTA: 26 players fetched
DET: 43 players fetched
CBJ: 43 players fetched
ANA: 45 players fetched
NYI: 43 players fetched
LAK: 47 players fetched
NJD: 44 players fetched
STL: 47 players fetched
NSH: 44 players fetched
SJS: 42 players fetched
FLA: 44 players fetched
WPG: 43 players fetched
SEA: 26 players fetched
TOR: 50 players fetched
CGY: 40 players fetched
NYR: 27 players fetched
CHI: 43 players fetched
VAN: 45 players fetched

Total players collected: 1292

In [ ]:
# Validate the complete players dataset from all NHL teams
print("Total players:", len(players_df))

print("\nMissing values:")
print(players_df.isnull().sum())

print("\nDuplicate player IDs:",
      players_df["player_id"].duplicated().sum())

print("\nUnique teams:",
      players_df["team_abbrev"].nunique())

print("\nUnique positions:")
print(players_df["position"].value_counts())

print("\nNegative height values:",
      (players_df["height_cm"] < 0).sum())

print("Negative weight values:",
      (players_df["weight_kg"] < 0).sum())

Total players: 1292

Missing values:
team_abbrev         0
player_id           0
first_name          0
last_name           0
position            0
jersey_number     141
birth_date          0
birth_country       0
height_cm           0
weight_kg           0
shoots_catches      8
headshot_url        0
dtype: int64

Duplicate player IDs: 0

Unique teams: 32

Unique positions:
position
D    413
C    355
R    194
L    188
G    142
Name: count, dtype: int64

Negative height values: 0
Negative weight values: 0

In [ ]:
# Fetch the 2025-2026 season schedule for Colorado Avalanche
team_abbrev = "COL"

schedule_url = (
    f"https://api-web.nhle.com/v1/club-schedule-season/"
    f"{team_abbrev}/20252026"
)

# Send the schedule API request
schedule_response = requests.get(schedule_url)

# Check whether the API request was successful
print("Status code:", schedule_response.status_code)

# Convert the response into a Python dictionary
schedule_data = schedule_response.json()

# Display the top-level keys
print("Response keys:", schedule_data.keys())

Status code: 200
Response keys: dict_keys(['previousSeason', 'currentSeason', 'nextSeason', 'clubTimezone', 'clubUTCOffset', 'games'])

In [ ]:
# Inspect the first game record to understand the schedule data structure
first_game = schedule_data["games"][0]

# Display the available fields in the game record
print("Game fields:")
print(first_game.keys())

# Display the complete first game record
print("\nFirst game record:")
print(first_game)

Game fields:
dict_keys(['id', 'season', 'gameType', 'gameDate', 'venue', 'neutralSite', 'startTimeUTC', 'easternUTCOffset', 'venueUTCOffset', 'venueTimezone', 'gameState', 'gameScheduleState', 'tvBroadcasts', 'awayTeam', 'homeTeam', 'periodDescriptor', 'gameOutcome', 'winningGoalie', 'winningGoalScorer'])

First game record:
{'id': 2025010103, 'season': 20252026, 'gameType': 1, 'gameDate': '2025-09-21', 'venue': {'default': 'Magness Arena'}, 'neutralSite': True, 'startTimeUTC': '2025-09-21T23:00:00Z', 'easternUTCOffset': '-04:00', 'venueUTCOffset': '-06:00', 'venueTimezone': 'America/Denver', 'gameState': 'FINAL', 'gameScheduleState': 'OK', 'tvBroadcasts': [], 'awayTeam': {'id': 21, 'commonName': {'default': 'Avalanche'}, 'placeName': {'default': 'Colorado'}, 'placeNameWithPreposition': {'default': 'Colorado', 'fr': 'du Colorado'}, 'abbrev': 'COL', 'logo': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg', 'darkLogo': 'https://assets.nhle.com/logos/nhl/svg/COL_dark.svg', 'awaySplitSquad': True, 'score': 5}, 'homeTeam': {'id': 68, 'commonName': {'default': 'Mammoth'}, 'placeName': {'default': 'Utah'}, 'placeNameWithPreposition': {'default': 'Utah', 'fr': "de l'Utah"}, 'abbrev': 'UTA', 'logo': 'https://assets.nhle.com/logos/nhl/svg/UTA_light.svg?season=20252026', 'darkLogo': 'https://assets.nhle.com/logos/nhl/svg/UTA_dark.svg?season=20252026', 'homeSplitSquad': True, 'score': 1}, 'periodDescriptor': {'number': 3, 'periodType': 'REG', 'maxRegulationPeriods': 3}, 'gameOutcome': {'lastPeriodType': 'REG'}, 'winningGoalie': {'playerId': 8485473, 'firstInitial': {'default': 'I.'}, 'lastName': {'default': 'Posch'}}, 'winningGoalScorer': {'playerId': 8484149, 'firstInitial': {'default': 'G.'}, 'lastName': {'default': 'Brindley'}}}

In [ ]:
# Extract required game information from the Colorado schedule
games_data = []

for game in schedule_data["games"]:
    games_data.append({
        "game_id": game["id"],
        "season": str(game["season"]),
        "game_type": game["gameType"],
        "game_date": game["gameDate"],
        "home_team_abbrev": game["homeTeam"]["abbrev"],
        "away_team_abbrev": game["awayTeam"]["abbrev"],
        "home_score": game["homeTeam"].get("score"),
        "away_score": game["awayTeam"].get("score"),
        "game_state": game["gameState"],
        "venue_name": game["venue"]["default"]
    })

# Convert the extracted games into a DataFrame
games_df = pd.DataFrame(games_data)

# Display the first few game records
display(games_df.head())

# Display the total number of games
print("Total games:", len(games_df))

,game_id,season,game_type,game_date,home_team_abbrev,away_team_abbrev,home_score,away_score,game_state,venue_name
0,2025010103,20252026,1,2025-09-21,UTA,COL,1,5,FINAL,Magness Arena
1,2025010104,20252026,1,2025-09-21,COL,UTA,3,2,FINAL,Ball Arena
2,2025010051,20252026,1,2025-09-27,COL,DAL,4,1,FINAL,Ball Arena
3,2025010070,20252026,1,2025-09-30,COL,VGK,4,2,FINAL,Ball Arena
4,2025010074,20252026,1,2025-10-01,VGK,COL,2,1,FINAL,T-Mobile Arena

Total games: 101

In [ ]:
# Create an empty list to store game records from all NHL teams
all_games_data = []

# Fetch the season schedule for every NHL team
for team_abbrev in teams_df["team_abbrev"]:

    # Build the schedule API URL
    schedule_url = (
        f"https://api-web.nhle.com/v1/club-schedule-season/"
        f"{team_abbrev}/20252026"
    )

    # Send the API request
    response = requests.get(schedule_url)

    # Process the response only when the request is successful
    if response.status_code == 200:

        # Convert the JSON response into a Python dictionary
        schedule = response.json()

        # Extract every game from the team's schedule
        for game in schedule.get("games", []):

            all_games_data.append({
                "game_id": game["id"],
                "season": str(game["season"]),
                "game_type": game["gameType"],
                "game_date": game["gameDate"],
                "home_team_abbrev": game["homeTeam"]["abbrev"],
                "away_team_abbrev": game["awayTeam"]["abbrev"],
                "home_score": game["homeTeam"].get("score"),
                "away_score": game["awayTeam"].get("score"),
                "game_state": game["gameState"],
                "venue_name": game["venue"].get("default")
            })

        print(f"{team_abbrev}: {len(schedule.get('games', []))} games fetched")

    else:
        print(f"{team_abbrev}: API request failed - {response.status_code}")

    time.sleep(0.5)

# Convert all collected game records into a DataFrame
games_df = pd.DataFrame(all_games_data)

# Display the total number of collected game records
print("\nTotal game records before deduplication:", len(games_df))

COL: 101 games fetched
CAR: 107 games fetched
DAL: 94 games fetched
BUF: 101 games fetched
TBL: 96 games fetched
MTL: 107 games fetched
MIN: 99 games fetched
BOS: 94 games fetched
OTT: 92 games fetched
PIT: 95 games fetched
PHI: 99 games fetched
WSH: 88 games fetched
VGK: 111 games fetched
EDM: 96 games fetched
UTA: 95 games fetched
DET: 90 games fetched
CBJ: 89 games fetched
ANA: 101 games fetched
NYI: 88 games fetched
LAK: 93 games fetched
NJD: 89 games fetched
STL: 88 games fetched
NSH: 88 games fetched
SJS: 88 games fetched
FLA: 89 games fetched
WPG: 88 games fetched
SEA: 88 games fetched
TOR: 88 games fetched
CGY: 90 games fetched
NYR: 88 games fetched
CHI: 88 games fetched
VAN: 88 games fetched

Total game records before deduplication: 2996

In [208]:
import pandas as pd

# Convert all fetched game records into a DataFrame
games_df = pd.DataFrame(all_games_data)

print("Raw game records:", len(games_df))
print("\nColumns:")
print(games_df.columns.tolist())

display(games_df.head())

Raw game records: 2996

Columns:
['game_id', 'season', 'game_type', 'game_date', 'home_team_abbrev', 'away_team_abbrev', 'home_score', 'away_score', 'game_state', 'venue_name']

,game_id,season,game_type,game_date,home_team_abbrev,away_team_abbrev,home_score,away_score,game_state,venue_name
0,2025010103,20252026,1,2025-09-21,UTA,COL,1,5,FINAL,Magness Arena
1,2025010104,20252026,1,2025-09-21,COL,UTA,3,2,FINAL,Ball Arena
2,2025010051,20252026,1,2025-09-27,COL,DAL,4,1,FINAL,Ball Arena
3,2025010070,20252026,1,2025-09-30,COL,VGK,4,2,FINAL,Ball Arena
4,2025010074,20252026,1,2025-10-01,VGK,COL,2,1,FINAL,T-Mobile Arena

In [209]:
# Check duplicate game IDs

print("Total game records:", len(games_df))
print("Unique game IDs:", games_df["game_id"].nunique())
print("Duplicate game records:", games_df["game_id"].duplicated().sum())

Total game records: 2996
Unique game IDs: 1498
Duplicate game records: 1498

In [210]:
# Show duplicate games, if any

duplicate_games = games_df[
    games_df["game_id"].duplicated(keep=False)
].sort_values("game_id")

display(duplicate_games.head(20))

,game_id,season,game_type,game_date,home_team_abbrev,away_team_abbrev,home_score,away_score,game_state,venue_name
1654,2025010001,20252026,1,2025-09-21,LAK,ANA,3,1,FINAL,Toyota Arena
1843,2025010001,20252026,1,2025-09-21,LAK,ANA,3,1,FINAL,Toyota Arena
2642,2025010002,20252026,1,2025-09-21,EDM,CGY,2,3,FINAL,Rogers Place
1284,2025010002,20252026,1,2025-09-21,EDM,CGY,2,3,FINAL,Rogers Place
2643,2025010003,20252026,1,2025-09-21,CGY,EDM,0,3,FINAL,Scotiabank Saddledome
1285,2025010003,20252026,1,2025-09-21,CGY,EDM,0,3,FINAL,Scotiabank Saddledome
2289,2025010004,20252026,1,2025-09-21,NSH,FLA,5,0,FINAL,Bridgestone Arena
2113,2025010004,20252026,1,2025-09-21,NSH,FLA,5,0,FINAL,Bridgestone Arena
2290,2025010005,20252026,1,2025-09-21,NSH,FLA,5,3,FINAL,Bridgestone Arena
2114,2025010005,20252026,1,2025-09-21,NSH,FLA,5,3,FINAL,Bridgestone Arena
2378,2025010006,20252026,1,2025-09-21,WPG,MIN,2,3,FINAL,Canada Life Centre
606,2025010006,20252026,1,2025-09-21,WPG,MIN,2,3,FINAL,Canada Life Centre
2732,2025010007,20252026,1,2025-09-21,NJD,NYR,3,5,FINAL,Prudential Center
1936,2025010007,20252026,1,2025-09-21,NJD,NYR,3,5,FINAL,Prudential Center
1755,2025010008,20252026,1,2025-09-21,NYI,PHI,2,3,FINAL,UBS Arena
986,2025010008,20252026,1,2025-09-21,NYI,PHI,2,3,FINAL,UBS Arena
2026,2025010009,20252026,1,2025-09-21,CBJ,STL,4,1,FINAL,Nationwide Arena
1565,2025010009,20252026,1,2025-09-21,CBJ,STL,4,1,FINAL,Nationwide Arena
2554,2025010010,20252026,1,2025-09-21,OTT,TOR,3,4,FINAL,Canadian Tire Centre
799,2025010010,20252026,1,2025-09-21,OTT,TOR,3,4,FINAL,Canadian Tire Centre

In [211]:
# Remove duplicate games based on game_id
games_df = games_df.drop_duplicates(subset=["game_id"], keep="first").copy()

print("Unique game records:", len(games_df))

Unique game records: 1498

In [212]:
print("Shape:", games_df.shape)

print("\nDuplicate game IDs:")
print(games_df["game_id"].duplicated().sum())

print("\nMissing values:")
print(games_df.isnull().sum())

print("\nGame states:")
print(games_df["game_state"].value_counts(dropna=False))

print("\nSample data:")
display(games_df.head(10))

Shape: (1498, 10)

Duplicate game IDs:
0

Missing values:
game_id             0
season              0
game_type           0
game_date           0
home_team_abbrev    0
away_team_abbrev    0
home_score          0
away_score          0
game_state          0
venue_name          0
dtype: int64

Game states:
game_state
OFF      1394
FINAL     104
Name: count, dtype: int64

Sample data:

,game_id,season,game_type,game_date,home_team_abbrev,away_team_abbrev,home_score,away_score,game_state,venue_name
0,2025010103,20252026,1,2025-09-21,UTA,COL,1,5,FINAL,Magness Arena
1,2025010104,20252026,1,2025-09-21,COL,UTA,3,2,FINAL,Ball Arena
2,2025010051,20252026,1,2025-09-27,COL,DAL,4,1,FINAL,Ball Arena
3,2025010070,20252026,1,2025-09-30,COL,VGK,4,2,FINAL,Ball Arena
4,2025010074,20252026,1,2025-10-01,VGK,COL,2,1,FINAL,T-Mobile Arena
5,2025010092,20252026,1,2025-10-04,DAL,COL,3,2,FINAL,American Airlines Center
6,2025020003,20252026,2,2025-10-07,LAK,COL,1,4,OFF,Crypto.com Arena
7,2025020018,20252026,2,2025-10-09,COL,UTA,2,1,OFF,Ball Arena
8,2025020034,20252026,2,2025-10-11,COL,DAL,4,5,OFF,Ball Arena
9,2025020039,20252026,2,2025-10-13,BUF,COL,1,3,OFF,KeyBank Center

In [214]:
# Save cleaned games data to CSV
games_df.to_csv("../data/games_cleaned.csv", index=False)

print("games_cleaned.csv created successfully!")
print("Rows:", len(games_df))

games_cleaned.csv created successfully!
Rows: 1498